### ISSUE TITLE
프로젝트 관리 툴 Trello에서 Github Project로 이동

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#1]
- [기존 트렐로 보드](https://trello.com/b/319F9e5q/%ED%8E%98%EB%AF%B8%EC%9C%84%ED%82%A4-%EA%B0%9C%EB%B0%9C%ED%8C%80)
- [새 Github Project Board](https://github.com/orgs/femiwiki/projects/1)

2018년 21일 디스코드 채팅에서 프로젝트 관리를 위해 사용하는 서비스를 기존 트렐로에서 깃헙 프로젝트 보드로 옮기기로 하였습니다.
- 장점: 깃헙 이슈랑 연동되기 때문에 편하다.
- 단점: 스마트폰 앱은 따로 없다.
- 기타: 트렐로와 마찬가지로 공짜

**Comment by simnalamburt** [comment]
트렐로에 있던것 모두 옮겨왔다.
