### ISSUE TITLE
Zapier 대체하기

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#100]
현재 페미위키에서는 [Zapier]의 Starter Plan을 사용중이며 이를 통해 다음을 처리하고 있습니다. (Starter Plan 요금은 달에 20 USD이며 자세한 사용 제한은 https://zapier.com/app/billing/plans 참고)

- 페미위키 Admin 보낸 메일 - 메일알림: G메일을 통해 Admin@femiwiki.com에서 메일을 보냈다면 디스코드 운영팀 채널에 알립니다.
- 페미위키 지메일 INBOX -디스코드 메일알림: Admin@femiwiki.com으로 메일이 왔다면 디스코드 운영팀 채널에 알립니다.
- dicord_weekly_GA_report: 한 주에 한 번씩 통계를 요약해서 디스코드 운영팀 채널에 올립니다.
- 인스타그램 페미위키 새 포스팅: 인스타그램 페미위키 계정에 새 포스트를 올렸다면 디스코드 운영팀 채널에 알립니다.
- 페미위키 페이스북 포스팅 - 디스코드 sns alert: 페이스북 페이지에 새 포스트가 올라오면 디스코드 운영팀 채널에 알립니다.
- 트위터 페미위키 URL 공유, 언급 - sns모니터링: 트위터에 페미위키를 태그한 포스트가 있으면 디스코드 운영팀 채널에 알립니다.

이를 대체할 수 있는가 알아보고 대체합니다.

- [Integromat]
- [Automate.io]
- AWS Lambda
- Webhook
- ~~[IFTTT]~~ &rarr; https://github.com/femiwiki/femiwiki/issues/95
- ~~[Microsoft Flow]~~ &rarr; https://github.com/femiwiki/femiwiki/issues/100#issuecomment-541496150

[zapier]: https://zapier.com/
[integromat]: https://www.integromat.com
[ifttt]: https://ifttt.com
[microsoft flow]: https://flow.microsoft.com/
[automate.io]: https://automate.io/

**Comment by lens0021** [comment]
현재(코멘트 작성시점) 각 작업을 처리하고 있는 서비스입니다.

| 작업 | Zapier | Integromat |
|--|--|--|
| Gmail | | :heavy_check_mark: |
| 트위터 | :heavy_check_mark: | |
| 페이스북 | | :heavy_check_mark: |
| 인스타그램 | | :heavy_check_mark: |
| 주간 GA | | :heavy_check_mark: |

-------------------

구글에서 `alternative` + `zapier`로 검색해서 대체할 만한 무료 틀을 찾고자 했으며, 일단 나온 결과 중에서 제 임의로 Integromat를 사용해 보았습니다.

Integromat를 먼저 써 본 이유는 Integromat가 무료로 한 달에 1000개의 오퍼레이션을 사용할 수 있어서 입니다. 수가 많은 만큼 단점이 있을 거 같아서 일단 첫 번째로 골라봤습니다.

다만 Zapier와는 다음과 같은 용어 차이가 있습니다.

| Zapier | Integromat |
|--|--|
| Zap | Scenario |
| Task | Operation |

또 태스크와 오퍼레이션은 정확히 일치하는 개념은 아닌 것으로 보입니다.

- https://zapier.com/help/manage/tasks/understand-tasks-in-zapier
- https://support.integromat.com/hc/en-us/articles/360001985113-Counting-the-number-of-operations

큰 차이점은 Zapier는 트리거가 작동하지 않으면 태스크의 숫자로 치지 않는 데 반해 Integromat는 아무런 일이 일어나지 않아도 조회 자체가 카운트되는 것 같습니다.

그 외 시나리오들을 만들어봤을 때 크게 저해되는 부분은 없었으나, 트위터의 경우 Zapier에서 했던 것과 비슷하게 꾸리는 것이 어려워 보입니다.

<details>
<p>Integromat는 이메일이나 몇 서비스에 대해서는 "Watch"로 시작하는 트리거를 제공하여 같은 메시지를 중복해서 처리하지 않는 것이 가능한 듯합니다. 그러나 트위터 검색의 경우에는 그렇지 않아 검색 시점에서 검색 결과를 지정한 숫자 만큼 가져오는 것만이 가능해 보이고, 중복된 트윗이 걸렸는지 어땠는지는 직접 처리하여야 하는 듯합니다. 이는 Zapier가 한 트윗을 처리하면 다시 처리하지 않는 것에 비하여 다소 불편한 상황입니다.</p>
<p>대신 Integromat는 데이터베이스를 용량 내로 하나 꾸려서 사용할 수 있어, 확인된 트윗의 ID를 데이터베이스에 담아두고 검색될 때마다 확인하는 것이 가능할 거 같아 그렇게 해보았지만, 일단 검색을 하고 그 다음에 확인을 하기 때문에 검색 결과 자체가 오퍼레이션으로 판정되는 것 같습니다, 이것도 사용이 어려운 부분입니다.</p>
</details>

**Comment by lens0021** [comment]
[Microsoft Flow](Microsoft Flow)의 무료 플랜이 15분 간격의 달 750번의 실행을 지원한다는 글들이 많은데 공식 홈페이지에는 무료 플랜에 대한 내용이 없습니다. 무료 체험 기간을 잘못 적은 건지 아니면 개인 개발자용 무료 사용을 잘못 적은 건지 아니면 그냥 홈페이지에서만 누락된 건지 구분이 안 됩니다.

**Comment by lens0021** [comment]
| ![image](https://user-images.githubusercontent.com/28209361/66728862-84a3d780-ee82-11e9-9e37-89864e36ec7d.png) |
|--|

Flow는 위와 같이 웹훅이 유료이고("이러한 기능을 사용하려면 회사 또는 학교 계정이 필요하며, 개인 전자 메일을 사용 중입니다. 이러한 기능을 사용해 보려면 회사 또는 학교 전자 메일을 사용하거나 새 조직 계정을 만들어 지금 평가판에 등록할 수 있습니다.") 디스코드도 따로 없는 것 같습니다.

**Comment by lens0021** [comment]
중간 보고입니다.

Zapier 유료 플랜을 대체하는 것이 한 서비스만으론 어렵다고 생각되어 여러 서비스를 사용하게 되었고 그 대신 로그인이 페미위키 구글 계정으로 가능한 서비스를 선택하였습니다. 이메일과 페이스북, 인스타그램, GA 자동 보고는 Integromat로, 트위터 모니터링은 Automate.io로 대체하였습니다. Zapier는 현재 처리 중인 작업이 없으며 FAQ에서 플랜 변경이 자유로운 것을 확인하고 무료 플랜으로 전환한 상태입니다.

각 서비스의 특징 및 선택하게 된 이유에 대한 설명입니다.

Integromat는 한 달에 1000번의 작업을 수행할 수 있다고 하지만 메일함에 메일이 왔는지 없는지 확인하는 것 자체를 수행횟수로 치기 때문에 15분 간격으로 계속 확인하려면 확인만 한 달에 2880번을 해야하는 문제가 있습니다. 대신 확인 간격을 늘리거나, 새벽 시간대는 확인을 하지 않는 방법으로 이를 유연하게 조절할 수 있다는 점이 저희에게 유리한 것 같아 사용하고자 합니다. 당장은 새벽 2~6시를 제외하고 한 시간에 한 번씩, 즉 하루에 20번 메일함을 확인하게 하여, 한달이면 약 600번을 확인하게 조절했습니다. 확인 뿐 아니라 메일함에 새 메일이 있다면 이것을 처리하는 데에도 작업 횟수가 들기 때문에 일단 여유를 많이 두었으며, 사용해가며 조절하면 되겠습니다.

Automate.io는 Zapier와 비슷한 트위터 모니터링을 제공하면서, 한 달 무료 수행이 250회 가능하여 선택하게 되었습니다. 저희 자동 트윗이 한 달 약 150개이니, 이것들을 제외하지 못 하더라도 Zapier 무료 플랜과 비슷한 숫자는 이용 가능해 보입니다.

**Comment by lens0021** [comment]
(추가) 도커 웹훅을 디스코드 웹훅으로 변환하는 것이 무료플랜 안에서 사용가능해 보여 Zapier를 다시 사용하고 있습니다.

**Comment by lens0021** [comment]
다음 서비스 한 달 사용량 초기일이 다가와 사용량 정리해 올립니다.

- Automate.io
  - Action quota resets in 1 day
  - ACTIONS: 224/250
- integromat.com
  - Usage reset: 2019년 11월 13일 오후 2:07
  - Operations: Used 85 % of 1,000
  - Data transfer: Used 2 % of 100.0 MB

적절해 보이며 이만 이슈 닫습니다.

**Comment by simnalamburt** [comment]
이제보니 Zapier의 오픈소스 대체재같은것도 있네유 https://github.com/huginn/huginn
