### ISSUE TITLE
회원가입할 때 비밀번호 정책 표시하기

### ISSUE THREAD

**Issue by love-adela** [femiwiki/femiwiki#120]
사용자에게 비밀번호 등록이 실패하는 이유를 placeholder로 표시하기

**Comment by lens0021** [comment]
Placeholder의 경우 [https://femiwiki.com/w/MediaWiki:Createacct-yourpassword-ph](https://femiwiki.com/w/MediaWiki:Createacct-yourpassword-ph)를 편집하면 수정됩니다, 다만 내용이 고정되어서 '일반사용자는 8자 이상, 관리자는 10글자 이상이어야 함' 같은 긴 내용을 전달할 수는 없을 것 같고, 어쨌든 8자 이상이라고만 적을까요?

**Comment by simnalamburt** [comment]
넵

**Comment by lens0021** [comment]
이슈가 등록 실패 버그(조건을 알 수 없음)과 비밀번호 정책 표시 두 가지라고 생각되는데 그 중 후자만 다루는 이슈로 생각하고 수정 후 닫겠습니다.

**Comment by lens0021** [comment]
![image](https://user-images.githubusercontent.com/28209361/68828410-f1f89180-06e8-11ea-9d3c-d7c90bbd6333.png)

https://femiwiki.com/w/Special:Redirect/revision/152508 문서 생성하여 수정되었습니다.
