### ISSUE TITLE
원본편집기에서 커서 위치 표시가 이상함

### ISSUE THREAD

**Issue by simnalamburt** [femiwiki/femiwiki#136]
OS: Windows 10, Version 1909
Browser: Firefox 71.0 x86-64

![a](https://user-images.githubusercontent.com/4435445/71270492-11907300-2395-11ea-89bb-8ff7e4a689e0.gif)

**Comment by lens0021** [comment]
햄버거 메뉴에서 문법강조가 켜져 있을 때 있는 증상입니다.

**Comment by simnalamburt** [comment]
혹시 에디터 확장기능쪽 Known Issue면 업스트림 이슈트래커 링크같은게 있나여?

**Comment by lens0021** [comment]
https://phabricator.wikimedia.org/T238678 인 것 같습니다
