### ISSUE TITLE
디스코드 바뀐글 알림에 무의미한 문자열이 끼어있음

### ISSUE THREAD

**Issue by simnalamburt** [femiwiki/femiwiki#137]
![image](https://user-images.githubusercontent.com/4435445/71280708-55887580-239f-11ea-8454-3d6921e4f73d.png)

`$1` 라는 글자가 계속 들어있네요

**Comment by lens0021** [comment]
https://github.com/kulttuuri/DiscordNotifications/pull/59 을 참고해주세요 포크에서는 체리픽 했기 때문에 오늘 점검에서 수정될 예정입니다

**Comment by lens0021** [comment]
수정되었습니다
