### ISSUE TITLE
벡터 스킨(Vector Skin) 제공 중단 필요성/방법 검토

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#143]
페미위키에서는 페미위키 스킨과 더불어 벡터 스킨 사용이 가능합니다.

* https://femiwiki.com?useskin=femiwiki
* https://femiwiki.com?useskin=vector

스킨은 위와 같이 URL에 파라미터로 전달하거나, 각 사용자가 환경설정에서 반영구적으로 변경할 수 있습니다.

그러나 벡터 스킨의 사용량이 페미위키 스킨에 비해 매우 적어 모든 문서와 특수 기능에 대해 상태를 점검 하는 소요가 상대적으로 큽니다.

아예 지원을 중단하거나, 혹은 고급 유저만 설정할 수 있도록 환경 설정에서 숨길 필요성이 있습니다.

**Comment by simnalamburt** [comment]
스킨 선택하는 UI에 "기본 스킨 이외의 스킨을 사용하면 페이지가 이상하게 표시될 수 있다"는 경고문구를 삽입하고, Vector나 커스텀 스킨 사용은 지금처럼 허락하되 개발자 지원은 멈추는 방식으로 하면 어떨까요

**Comment by lens0021** [comment]
괜찮아 보입니다. 환경 설정에 경고 문구 삽입은 어떻게 할지 모르겠지만 스킨 변경 직후에 팝업 같은 경고 띄워도 좋겠습니다.

**Comment by revi** [comment]
MediaWiki:Skinname-vector 에 미지원 내용을 넣으면 되지 않을까요?

**Comment by lens0021** [comment]
혹시 revi님 이 이슈 assign 해드려도 될까요?
운영팀·개발팀 합류하신 후에 아직 위키에서 권한 안 드렸는데 다음 권한 부여할게용
- 운영팀(`femiwiki-team`): 운영팀 기본 권한. 보호된 글 편집 가능.
- 인터페이스 관리자: (설명 생략)

**Comment by revi** [comment]
[벡터 (이 스킨은 페미위키에서 공식적으로 지원하지 않습니다.)](https://femiwiki.com/index.php?diff=158889)

<img width="80%" alt="image" src="https://user-images.githubusercontent.com/7630875/75095930-4ad7a000-55dd-11ea-9d89-a513e46817b8.png">

오타는 고쳤습니다 <_<
