### ISSUE TITLE
CI에 브라우저 엔진 사용한 E2E 테스트넣기

### ISSUE THREAD

**Issue by simnalamburt** [femiwiki/femiwiki#145]
셀레니움이나 puppeteer같은걸 써서 E2E 테스트를 해보자

**Comment by lens0021** [comment]
위키미디어는 미디어위키-실리니움(https://phabricator.wikimedia.org/diffusion/MSEL/)을 사용하는데 미디어위키용 기능들이 있거나 해서 쓰기 좋은 면이 있다면 이걸 쓰면 좋을 것 같습니다. 아마 Quibble(이거도 미디어위키 전용)에서 지원한다든가 할 것 같습니다.

**Comment by lens0021** [comment]
Enable selenium test

- [ ] AchievementBadges
- [ ] DiscordNotifications
- [ ] FacetedCategory
- [ ] Sanctions
- [ ] UnifiedExtensionForFemiwiki
- PageViewInfoGA - it just provides api
- ? FemiwikiSkin

Add tests

- [x] AchievementBadges
- [ ] DiscordNotifications
- [x] FacetedCategory
- [ ] Sanctions
- [ ] UnifiedExtensionForFemiwiki
- PageViewInfoGA - it just provides api
- ? FemiwikiSkin

**Comment by simnalamburt** [comment]
제가 엄청 바쁘던 시기에 엄청난 일이 진행이 되고있었군용..

**Comment by lens0021** [comment]
첫삽은 떴으니까 이슈 닫습니다
근데 [docker-mediawiki](https://github.com/femiwiki/docker-mediawiki)에서나 [nomad](https://github.com/femiwiki/nomad)도 실행하면 좋을것 같긴 한데 필요하시면 feel free to open
