### ISSUE TITLE
EBS 용량 모니터링하기

### ISSUE THREAD

**Issue by simnalamburt** [femiwiki/femiwiki#150]
EBS가 차기 전에 미리 알아내야합니다

**Comment by lens0021** [comment]
[CloudWatch Agent](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Install-CloudWatch-Agent.html)에 의해 수집되는 정보 중 관련된 게 있어서 이를 설치하기로

Metric | Description
-- | --
disk_free | Free space on the disks. Unit: Bytes
disk_inodes_free | The number of available index nodes on the disk. Unit: Count
disk_inodes_total | The total number of index nodes reserved on the disk. Unit: Count
disk_inodes_used | The number of used index nodes on the disk. Unit: Count
disk_total | Total space on the disks, including used and free. Unit: Bytes
disk_used | Used space on the disks. Unit: Bytes
disk_used_percent | The percentage of total disk space that is used. Unit: Percent

**Comment by lens0021** [comment]
https://github.com/femiwiki/infra/commit/928eacbe77572715f6c7c3c011f1c00dcaeba24a
