### ISSUE TITLE
대문 랭킹페이지 치우고 후원링크 달기

### ISSUE THREAD

**Issue by love-adela** [femiwiki/femiwiki#154]
2020년 1월 OKR 항목 중 일부입니다.
* [x] 대문 랭킹 페이지 삭제
* [x] [후원링크](https://femiwiki.com/w/%ED%8E%98%EB%AF%B8%EC%9C%84%ED%82%A4:%ED%9B%84%EC%9B%90%ED%95%98%EA%B8%B0) 대문 중 눈에 잘 띄는 곳으로 옮기기

**Comment by lens0021** [comment]
페미위키에 공지 비슷하게 글 올려놓았습니다 https://femiwiki.com/w/%EC%A3%BC%EC%A0%9C:Vfe6gwcmktzvo39l
