### ISSUE TITLE
 모든 도커 이미지 리포지터리에 Continuous Delivery 세팅하기

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#156]
깃헙의 매 푸시마다 도커 이미지를 빌드하여 레지스트리(도커헙이든 깃헙 패키지든)에 푸시하는 것을 목표로 하는데, 이는 현재도 그렇게 되어 있으나 다음을 수행할 수 있도록 새로 세팅합니다.

- 깃헙 액션에서의 빌드 https://github.com/femiwiki/femiwiki/issues/51
- 자동 버저닝 https://github.com/femiwiki/femiwiki/issues/56

랭킹봇과 트윗봇은 https://github.com/femiwiki/femiwiki/issues/160 에서 처리하기로 하고 이 이슈에서는 제외합니다.

#### 체크리스트

- 깃헙액션 작업할 도커 이미지 리포: (https://github.com/femiwiki?utf8=%E2%9C%93&q=docker-image+archived%3Afalse&type=&language=)
    - [x] [docker-mediawiki](https://github.com/femiwiki/docker-mediawiki)
    - [x] [docker-parsoid](https://github.com/femiwiki/docker-parsoid)
    - [x] [base-extensions](https://github.com/femiwiki/base-extensions)
    - [x] [base](https://github.com/femiwiki/base)
    - [x] [docker-restbase](https://github.com/femiwiki/docker-restbase)
    - [x] [backupbot](https://github.com/femiwiki/backupbot)
    - ~~tweetbot~~ https://github.com/femiwiki/tweetbot/issues/12
    - ~~rankingbot~~ https://github.com/femiwiki/tweetbot/issues/12
- 도커 액세스 토큰 Secrets 추가하기
    - [x] docker-mediawiki
    - [x] docker-parsoid
    - [x] base-extensions
    - [x] base
    - [x] docker-restbase
    - [x] backupbot
- 도커 허브 자동 빌드 끄고 Deploy Key 지워야 하는 리포:
  - [x] [mediawiki](https://hub.docker.com/repository/docker/femiwiki/mediawiki)
  - [x] [tweetbot](https://hub.docker.com/repository/docker/femiwiki/tweetbot)
  - [x] [parsoid](https://hub.docker.com/repository/docker/femiwiki/parsoid)
  - [x] [base-extensions](https://hub.docker.com/repository/docker/femiwiki/base-extensions)
  - [x] [base](https://hub.docker.com/repository/docker/femiwiki/base)
  - [x] [restbase](https://hub.docker.com/repository/docker/femiwiki/restbase)
  - [x] [rankingbot](https://hub.docker.com/repository/docker/femiwiki/rankingbot)
  - [x] [backupbot](https://hub.docker.com/repository/docker/femiwiki/backupbot)

**Comment by simnalamburt** [comment]
femiwiki/base, femiwiki/base-extensions 두 리포지터리가 사실 Docker Hub Automated Build가 빌드 레이어 캐싱을 지원 안해서 만들어진 적폐입니다. 이제 도커헙 빌드가 아니라 github actions를 쓰니까 뭔가 도커 빌드 캐시가 될법도 한데, 이번기회에 치울 수 없을라나요

**Comment by simnalamburt** [comment]
> 
> 
> femiwiki/base, femiwiki/base-extensions 두 리포지터리가 사실 Docker Hub Automated Build가 빌드 레이어 캐싱을 지원 안해서 만들어진 적폐입니다. 이제 도커헙 빌드가 아니라 github actions를 쓰니까 뭔가 도커 빌드 캐시가 될법도 한데, 이번기회에 치울 수 없을라나요

https://github.com/femiwiki/femiwiki/issues/167 에서 해결하기로함
