### ISSUE TITLE
이미지가 없는 문서더라도 Fallback으로 적절한 트위터 카드 이미지가 뜨도록 고치기

### ISSUE THREAD

**Issue by love-adela** [femiwiki/femiwiki#158]
SNS에 공유되는 링크에 파비콘을 띄우길 제안합니다.

**Comment by lens0021** [comment]
https://github.com/femiwiki/docker-mediawiki/issues/296 과 관련있어 보입니다. 이슈 혹시 더 자세히 설명 들을 수 있을까요?

**Comment by love-adela** [comment]
![0A54B132-EEF5-42C5-8368-9F488FD76AF3](https://user-images.githubusercontent.com/19512112/74102205-a0935d80-4b84-11ea-8a32-417dbcfb7620.jpeg)
 파비콘 설정을 통해 저 공백(?)에 페미위키 로고라도 보이게 하는게 어떨까요? 말씀하신 이슈와 연관되어 있어보이긴 하는데, 이슈 단위가 크네요. 조금씩 나눠서 진행하는건 어떨까요?

**Comment by lens0021** [comment]
그 뭐지... 업스트림에 PR 넣었습니다.. https://phabricator.wikimedia.org/T256935

**Comment by lens0021** [comment]
> 그 뭐지... 업스트림에 PR 넣었습니다.. https://phabricator.wikimedia.org/T256935

[OpenGraphMeta](https://www.mediawiki.org/wiki/Extension:OpenGraphMeta)가 너무 인기가 없어서.. [PageImages](https://www.mediawiki.org/wiki/Extension:PageImages)로 패치 넣어보는 게 나을 것 같습니다.

**Comment by lens0021** [comment]
https://gerrit.wikimedia.org/r/c/mediawiki/extensions/PageImages/+/700116 패치 머지되었고 미디어위키 1.37에 적용됩니다. 저희는 현재 1.36을 쓰고 있으므로 포크하고 체리픽킹해서 쓰겠습니다.

**Comment by lens0021** [comment]
Can confirm in https://cards-dev.twitter.com/validator:

![image](https://user-images.githubusercontent.com/28209361/127753485-1d1a1a62-f5eb-406b-9ad7-137738747fdd.png)
