### ISSUE TITLE
페미위키 관련 모든 소스코드 라이센스 통일하기

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#16]
"AGPL-3.0" 아니면 "(Apache-2.0 OR MIT)" 로 통일한 뒤, https://femiwiki.com/w/%ED%8E%98%EB%AF%B8%EC%9C%84%ED%82%A4:%EC%86%8C%EC%8A%A4_%EC%BD%94%EB%93%9C 문서의 잘못된 설명들도 고치기

#### Activity
 - Hyeon Kim added [this card](https://trello.com/c/lPWmIJWu) to To Do Apr 30 at 2:59 PM
 - Hyeon Kim joined this card Apr 30 at 2:59 PM
 - 낙엽 Jul 29 at 8:29 PM <blockquote>오래 진행되지 않아 제안/메모로 이동합니다</blockquote>
 - 낙엽 transferred this card from [FEMIWIKI](https://trello.com/b/zX0oXA4U) Sep 11 at 2:09 AM
 - Hyeon Kim Sep 16 at 5:30 AM <blockquote>AGPL-3.0으로 통일됨</blockquote>
 - Hyeon Kim moved this card from Backlog to Done Sep 16 at 5:30 AM

**Comment by lens0021** [comment]
크리에이티브 커먼즈 라이센스인 페미위키 스킨을 다른 라이선스로 바꾸어야 합니다(맞나요??)
- [ ] https://github.com/femiwiki/skin/blob/master/LICENSE
- [ ] https://github.com/femiwiki/skin/blob/master/skin.json#L8

**Comment by simnalamburt** [comment]
네 스킨도 AGPL-3.0 로 바꿉시다
