### ISSUE TITLE
 k3s에 퍼시스턴시 넣기

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#161]
[#116](https://github.com/femiwiki/femiwiki/issues/116)의 일부, k3s에 퍼시스턴시 넣기. 아래 두 옵션중 1 먼저 시도하고 안되면 2

  1. ~~k3s의 SQLite3 DB파일을 비롯한 로컬 데이터를 EBS에 따로 마운트시키기. 그렇게 해서 k3s DB 백업만으로 클러스터 복구가 잘 되는지 확인하기. 잘 된다면 k3s EC2 꺼질때에 자동으로 EBS 지워지게 만든 뒤 개발과정에서 릭난 EBS랑 모두 치우기~~
  2. ~~k3s EC2 Instance의 루트 볼륨 EBS를 인스턴스 재생성 할 때마다 새로 만드는게 아니라, 하나의 EBS를 계속 재사용하도록 하기~~

**Comment by lens0021** [comment]
`/var/lib/rancher/k3s`(Folder to hold state)를 백업/복구해 볼까 하는데 어떤 것들을 점검해야 하는지 잘 모르겠네요. 일단 문제가 발생하지 않는지와 `kubectl get pods -A` 결과만 비교해보려고 하는데 그러면 될까요?

**Comment by simnalamburt** [comment]
`kubectl get all -A` 가 같으면 될거같아요

**Comment by lens0021** [comment]
- 4GiB gp2 볼륨 하나 만들었습니다.
- `aws_instance.femiwiki_green`에게 `/dev/xvdf`로 attach했습니다
- 다음을 실행했습니다:
```sh
sudo mkfs -t xfs /dev/xvdf
sudo mkdir /data
sudo cp -r /var/lib/rancher/k3s/* /data
sudo umount /data
echo "UUID=$(blkid -s UUID -o value /dev/xvdf)  /var/lib/rancher/k3s  xfs  defaults,nofail  0  2" | sudo tee -a /etc/fstab
sudo mount -a
```
* `aws_instance.femiwiki_green`를 Reboot했습니다. `kubectl get all -A`는 `STATUS` 제외하면 동일했습니다.
* EBS를 Detach, `aws_instance.femiwiki_green`를 Stop, Disable termination protection, Terminate했습니다.

#### References
- https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-using-volumes.html

**Comment by lens0021** [comment]
accidently closed

**Comment by lens0021** [comment]
위 코멘트에서 묘사한 것처럼 인스턴스를 새로 띄워 `/var/lib/rancher/k3s/`만 복구해 보았을 때 `kubectl get all -A`의 차이는:

* `service`, `daemonset.apps`, `statefulset.apps`, `job.batch`에는 큰 차이가 없었고
* 일부 `pod`이 `Terminating`이 하나 `Running`이 하나 해서 둘씩 표시되고
* `replicaset.apps/traefik-xxxxxxxxx`가 둘이 되고

하는 등의 변화가 있었습니다.

그러나 `kubectl get all -A` 결과가 계속 변화하여 정확한 비교는 어려웠습니다. 왜 변하는지 잘 모르겠어서(왜 어떤 것이 계속 `Terminating`되고 있는지 등) 저는 일단 체크를 정확히 할 수 없을 것 같습니다. @simnalamburt 님께서 문제가 있는 건지 확인 혹은 실험해 주셔서 괜찮은 것 같으면 이슈 닫아주시면 감사하겠습니다.

**Comment by simnalamburt** [comment]
확인해보니 저런식으로 데이터를 보존해선 쿠버네티스 클러스터가 비정상적인 상태에 빠지네요. DB를 외부로 빼거나 DQLite를 써야할것같은데 둘다 걱정되는 부분이 있어서 어떻게 할지 고민을 해봐야겠습니다

- https://rancher.com/docs/k3s/latest/en/installation/ha/
- https://rancher.com/docs/k3s/latest/en/installation/ha-embedded/

**Comment by simnalamburt** [comment]
EBS StorageClass 대신 k3s 기본 로컬 스토리지 프로바이더를 써서 PVC를 관리하기로 함.

지금 도커스웜 인스턴스처럼 모든 데이터를 `/srv/*`에 저장하고, `/srv/*` 에 있는 파일들을 PVC에 마운트하되, `/srv` 디렉토리를 통째로 EBS에 마운트시키면 퍼시스턴시를 구현할 수 있을 것 같다.

- https://rancher.com/docs/k3s/latest/en/storage/

**Comment by lens0021** [comment]
https://github.com/femiwiki/femiwiki/issues/161#issuecomment-586270266 에 적힌 진행 중에 제 임의로 대충 한 게 있는데 혹시 싶어 적어둡니다.

- EBS 포맷을 AWS 문서에 적힌 예제와 같이 xfs으로 했습니다.
- Volume을 Attach 할 때 디바이스 이름 칸에 `/dev/sdf`이 자동완성 되어 있었는데 `/dev/xvdf`로 했습니다. 저희 루트 디바이스가 `/dev/xvda`여서 그거랑 같게 한 건데 의미가 있는 행동이었을까요?

**Comment by simnalamburt** [comment]
See https://github.com/femiwiki/infra/pull/41

**Comment by lens0021** [comment]
혹시 [https://github.com/femiwiki/femiwiki/issues/116#issuecomment-563277068](https://github.com/femiwiki/femiwiki/issues/116#issuecomment-563277068)과 그 아래 코멘트들에서 적어주신 시행착오 끝에 작성한 부분은 다 덜어지는 건가요?

**Comment by simnalamburt** [comment]
#116 에 써져있는대로 지금 띄워져있긴 한데, 그 결과 https://github.com/femiwiki/femiwiki/issues/161#issuecomment-586297054 이런 문제를 겪었고, https://github.com/femiwiki/femiwiki/issues/161#issuecomment-586564241 이렇게 해결을 해야만 하는데 아직 안한겁니다.

**Comment by lens0021** [comment]
stateful 한 것들은 다 `/srv/femiwiki.com` 아래 (클러스터와)마운트하게 하고 `/srv`는 (ec2와)마운트하게 했습니다. 재부팅 후에 DB 내용이 보존되어 있는 것을 확인했습니다.

인스턴스를 새로 만들었을 때도 퍼시스턴시가 있는지는 특별히 확인하지 않았습니다.

**Comment by simnalamburt** [comment]
재부팅 하고도 보존되었다면 인스턴스 껏킷해도 보존될것같긴 하네요

**Comment by simnalamburt** [comment]
고생 많으셨어욤
