### ISSUE TITLE
keybase 암호문 대신 1Password 로 옮기기

### ISSUE THREAD

**Issue by simnalamburt** [femiwiki/femiwiki#163]
비싸서 포기했었는데, 오픈소스 플젝에선 공짜로 쓸 수 있다고 한다.

참고: https://github.com/1Password/1password-teams-open-source#librewiki

**Comment by revi** [comment]
PS: 매년 갱신이고, 그럴 수밖에 없는 게 무료로 해주는 형식이 trial 기간을 +365일 해줍니다.

**Comment by simnalamburt** [comment]
어 혹시 갱신하는 절차가 좀 까다롭나요 아니면 큰 공수가 안드나요?

**Comment by revi** [comment]
그냥 신청 때도 '메일 한번 보내세요'라는 응답이 왔었는데요, 저도 쓴 지 3개월 돼서 갱신은 안해봤어요 <_<

**Comment by revi** [comment]
어짜피 신청할 때도 메일을 한 번 보내야 합니다.

**Comment by revi** [comment]
<img width="80%" alt="image" src="https://user-images.githubusercontent.com/7630875/74592027-a1cef980-5060-11ea-96df-dc4856870b0e.png">

신청이 아니라 문의할 게 있어서 메일을 보냈었네요... 여튼 org 계정은 생성했고 개별 사용자 계정 초대는... 허용된 도메인에서 오는 메일 주소를 쓰면 자동가입 or 관리자가 수동 초대를 해야 할 것 같네요. 신청 전에 조직 관리자를 두 명 이상 두어야 합니다.

**Comment by simnalamburt** [comment]
일단 저랑 레비님 2인이 소속된 상태이고, 이 상태에서 신청을 하겠습니다

**Comment by simnalamburt** [comment]
https://github.com/1Password/1password-teams-open-source/pull/185 에서 절차가 진행중입니다

**Comment by revi** [comment]
![FF2550BD-1CAD-4928-98DB-8B62A4C1892E](https://user-images.githubusercontent.com/7630875/75602447-940d7f80-5b08-11ea-825f-f71214c9f2d7.png)

승인됐네요 갱신 리마인더 해놨슴미다

**Comment by revi** [comment]
* Shared 저장소의 내용물은 1password 조직 내 모든 사용자가 볼 수 있음.
* 추가 저장소 생성 가능.
* Team 요금제에서는 그룹 생성 불가능.
* 따라서 추가 저장소 생성 시 접근 관리는 각 개인을 저장소 ACL에 추가하는 식으로 해야 함.

**Comment by simnalamburt** [comment]
레비님이 지금 비밀번호에 권한이 없어서 옮기는걸 못하시겠죠 아마?

**Comment by revi** [comment]
> 레비님이 지금 비밀번호에 권한이 없어서 옮기는걸 못하시겠죠 아마?

넹 온보딩 할 때도 비번은 이걸로 옮길 거라는 암묵적인 이해가 있었던 거 같아서 키베이스 추가 안 한 거 같아요

**Comment by simnalamburt** [comment]
기존 키베이스 암호문에 권한 있었던 사람들을 대상으로 초대 진행중

**Comment by simnalamburt** [comment]
이전 완료
