### ISSUE TITLE
"docker-mediawiki" 도커 이미지 빌드속도 최적화

### ISSUE THREAD

**Issue by simnalamburt** [femiwiki/femiwiki#167]
1. femiwiki/base, femiwiki/base-extensions 두 리포지터리가 사실 Docker Hub Automated Build가 빌드 레이어 캐싱을 지원 안해서 만들어진 적폐입니다. 이제 도커헙 빌드가 아니라 github actions를 쓰니까 뭔가 도커 빌드 캐시가 될법도 한데, 이번에 GitHub Actions로 대부분 옮겼으니 치울 수 있을 것 같습니다

2. 그 외에도 Dockerfile 구조를 개선해서 빌드속도를 올릴 부분도 있는것같습니다

**Comment by lens0021** [comment]
검색 중에 찾은 글입니다: https://github.community/t5/GitHub-Actions/Docker-layer-caching/td-p/41432

**Comment by simnalamburt** [comment]
망했내요 걍 현행유지할까요

**Comment by lens0021** [comment]
업데이트될 가능성을 기다리고 Blocked로 처리하나요 아니면 Close 하나요?

**Comment by simnalamburt** [comment]
오랜만에 보니까 구조를 싹 갈아서 빌드속도를 최적화할 건덕지가 좀 보이네요. 걍 제목을 빌드속도 최적화로 바꿀게요

**Comment by simnalamburt** [comment]
근데 저거 깃헙 레이어 캐시 기능이 지원되지 않을뿐이지 `/var/lib/docker` 밑부분을 잘 캐싱하면 될것같지 않나요?

**Comment by lens0021** [comment]
전 잘 모르겠습니다 :wink:

**Comment by simnalamburt** [comment]
👁️     👁️

**Comment by lens0021** [comment]
;; 저희 쓰는 액션에 전달인자로 캐시가 있긴 하네요
> https://github.com/elgohr/Publish-Docker-Github-Action#cache:
> Use cache when you have big images, that you would only like to build partially (changed layers).
>
> > CAUTION: Docker builds will cache non-repoducable commands, such as installing packages. If you use this option, your packages will never update. To avoid this, run this action on a schedule with caching disabled to rebuild the cache periodically.

**Comment by lens0021** [comment]
써먹을려고 더 보니까 대충 이런 내용입니다:
```
docker pull ${DOCKERNAME} 2>/dev/null; then
docker build --cache-from ${DOCKERNAME}" .
```

**Comment by simnalamburt** [comment]
뭐여 그럼 캐시 되는거아닌감

**Comment by lens0021** [comment]
거러초머

**Comment by lens0021** [comment]
옵션 줘봤는데 빌드 속도에 차이가 없는 것 같습니다 :sob:

**Comment by lens0021** [comment]
@revi 님 이 이슈 크게 세 부분으로 나눠서

1. `femiwiki/base`, `femiwiki/base-extensions` 를 `femiwiki/mediawiki`에 합치기
2. 도커 빌드 과정을 캐시하기
3. 지현님이 말씀하신 최적화

이렇게 나눠질 거 같은데 2번은 제가 찾아보는 걸로 하고 1번을 부탁드려도 될까요?

**Comment by lens0021** [comment]
> @lens0021 commented:
> 옵션 줘봤는데 빌드 속도에 차이가 없는 것 같습니다

일단 먼저 적을 게 액션 러너에서 `Run docker --version`해보면 "Docker version 3.0.10+azure"라고 나오며 buildkit은 UCP 3.2에서 번들되어서 사용이 불가합니다. 로그에도 보면

```
[Warning] One or more build-args [BUILDKIT_INLINE_CACHE] were not consumed
```

라고 나옵니다.

참고 삼아 [whoan/build-docker-images-using-cache](https://github.com/marketplace/actions/build-docker-images-using-cache)라는 액션이 있어 살펴 보았습니다.

- 캐싱 없는 빌드가 2~3분 걸리는 데 반해 이 액션을 통해 빌드하면 1분 좀 넘는 정도로 빌드가 완료됩니다. 로그에도 "Using cache"라는 문구가 스테이지마다 출력됩니다. ([로그](https://github.com/lens0021/docker-mediawiki/runs/486614041?check_suite_focus=true))
- 이 액션은 `BUILDKIT_INLINE_CACHE=1` 를 쓰는게 아니라 스테이지들을 각각 푸시하여 캐시로 사용합니다. 그래서 저희의 경우 `femiwiki/mediawiki-stages:1`, `femiwiki/mediawiki-stages:2`라고 푸시/풀 될 것입니다.

요지는 (제가 생각하기로) 저희 이미지는 스테이지가 있는데 `BUILDKIT_INLINE_CACHE=1`가 없이 빌드한 이미지의 경우 최종적으로 필요 없는 스테이지는 이미지에 포함을 안 하는 것 같으며, 그래서 그렇게 빌드한 이미지는 캐시로 못 쓰는 것 같습니다.

([Caching Docker layers on serverless build hosts with multi-stage builds, --target, and --cache-from](https://andrewlock.net/caching-docker-layers-on-serverless-build-hosts-with-multi-stage-builds---target,-and---cache-from/)라는 글에서는 예제에서 `builder`라는 스테이지를 만들어서 쓰는데 위와 같은 문제를 해결하기에 앞서 "Currently we have a problem - we want to reuse the build layers of the `builder` stage in our multi-stage Dockerfile, but we don't push those layers to a repository, so we can't pull them in subsequent builds."라고 설명하고 있습니다.)

그러나 whoan/build-docker-images-using-cache 액션을 직접 쓰기에는 

- 이 액션이 아직 커스텀 태그를 여럿 붙이는 게 불가능하여 저희 같은 경우는 태그가 빌드 때마다 바뀌는데 해당 태그로 pull을 해봤자 아무 것도 안 나오므로 latest를 쓸 게 아니면 캐싱 못 한다는 문제가 있습니다.
- 또 캐시를 도커 허브에 푸시하는 것도 좀 이상한 것 같습니다. `docker save`해서 그걸 `actions/cache`했다가 `docker load`하면 어떨까 합니다.

:dizzy: 
:dizzy_face:

**Comment by lens0021** [comment]
우선순위 내립니다

**Comment by lens0021** [comment]
> 일단 먼저 적을 게 액션 러너에서 `Run docker --version`해보면 "Docker version 3.0.10+azure"라고 나오며 buildkit은 UCP 3.2에서 번들되어서 사용이 불가합니다.

Ubuntu 20.04 LTS에서 Docker-Moby 버전 19.03.11+azure으로 다시 시도해 볼만 합니다. https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu2004-README.md

**Comment by lens0021** [comment]
> **Note**: The Ubuntu 20.04 virtual environment is currently provided as a preview only. The ubuntu-latest YAML workflow label still uses the Ubuntu 18.04 virtual environment.

[라고 그래서](https://docs.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners) blocked로 옮깁니다...

**Comment by lens0021** [comment]
ubuntu18 version 20200709.0에서 Docker-Moby이 3.0.13+azure에서 19.03.12+azure으로 올랐습니다. [1]

[1] https://github.com/actions/virtual-environments/commit/487c88b726392dda3077c6938c688a9601486763

**Comment by lens0021** [comment]
깃헙 액션 상에서 `DOCKER_BUILDKIT=1`[1]이랑 `--build-arg BUILDKIT_INLINE_CACHE=1`, `--cache-from`[2] 다 주고 두 번 돌렸더니 첫 번째에는 3분 정도 걸리던 빌드 스탭이 두 번째는 한 30초 정도로 끝났습니다.

[1] https://github.com/femiwiki/docker-mediawiki/commit/d929f7ae
[2] https://github.com/femiwiki/docker-mediawiki/commit/50a589b3

**Comment by lens0021** [comment]
@revi 님 ~ femiwiki/base, femiwiki/base-extensions, femiwiki/mediawiki 셋 합치는 것 아직 관심 있으신가요~??

**Comment by simnalamburt** [comment]
호오 `BUILDKIT_INLINE_CACHE=1` 같은게 생겼군요... 캐싱이 가능해져서 이제 세 이미지를 합칠 수 있겠네요
