### ISSUE TITLE
디스코드에 GitHub Actions 알림 안 오도록 고치기

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#170]
![image](https://user-images.githubusercontent.com/28209361/74604336-6d127f00-5100-11ea-92fe-a913faef0981.png)

요 메시지가 4시간마다 한번씩 나오는데 불필요해 보입니다.
실패한 경우가 아니라면 안 나오도록 고치면 좋을 것 같습니다.

**Comment by lens0021** [comment]
랭킹봇도 동일하여 수정하였습니다~

**Comment by revi** [comment]
[웹훅에서 설정 가능한 알림 종류](https://developer.github.com/v3/activity/events/types/) 리스트만 봤을 때는 actions 관련 훅이 하나도 없는 것 같은데요,,, checks 쪽은 커밋에 붙는 체크마크 쪽 설정 같고요.

**Comment by lens0021** [comment]
"[GitHub Actions use the Checks API to output statuses, results, and logs for a workflow.](https://help.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run)"라고 하니 그게 맞는 것 같은데, 근데 열심히 구글해봤는데 정확한 해결법을 못 찾겠어요

**Comment by lens0021** [comment]
두 개가 뜨는건 하나는 Check runs이고 하나는 Check suites라서 그런 것 같거든요, 일단 Check runs를 비활성화 했습니다

**Comment by simnalamburt** [comment]
깃헙액션 알림을 통째로 끄기로 결정함

**Comment by simnalamburt** [comment]
"Check Suites"를 끄면 되는거같은데 이게 맞는지는 모르겠음
![image](https://user-images.githubusercontent.com/4435445/75626910-d7521600-5c0e-11ea-9ae7-0f2df14c6f76.png)

**Comment by lens0021** [comment]
@love-adela 혹시 일단 꺼봐도 될까요?

**Comment by love-adela** [comment]
아 네! 그럼요!

**Comment by lens0021** [comment]
지금 꺼봤습니다 :smiley:

**Comment by simnalamburt** [comment]
GitHub Actions 알림이 정상적으로 뮤트된것같아 Close하겠습니다.
