### ISSUE TITLE
G Suite SPF, DKIM, DMARC

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#172]
페미위키 도메인으로 발송되는 스팸이 있는지 확인하고, 있다면 스팸이 받는 사용자 받은편지함으로 도착하지 못하도록 (표준 구현은 이메일 업체마다 다르지만) 저지

- [x] SPF (https://support.google.com/a/answer/33786) (아마존+구글)
- [x] Google G Suite DKIM (https://support.google.com/a/answer/174124)
- [x] AWS SES DKIM (이미 설정됨)
- [ ] DMARC 리포트 받아보기

**Comment by revi** [comment]
DMARC는 도메인에서 발송된 이메일 출처를 알려주는 서비스 (스팸 감지에 사용)인데 보고서가 xml이라 [예쁘게 보여주는 서비스](https://dmarc.postmarkapp.com/) 를 써야 할 것 같은데 주간 알림 서비스 보낼 메일을 어디로 해야 할 지 몰겠네요

**Comment by revi** [comment]
SES에서 메일을 보낼 테니까 SES도 포함하면 SPF는 @ 값에 `v=spf1 include:amazonses.com include:_spf.google.com ~all`를 넣어야 하겠네요. (이 외에 femiwiki.com 으로 메일을 보내는 서비스가 있다면 그 서비스에 대한 SPF 값도 추가해야 합니다)

DKIM은 AWS랑 Google에서 주는 값을 넣어야 하고요.

DMARC는 저거 다 하고 나서 생각해도 되겠어요

**Comment by revi** [comment]
DKIM은 AWS는 넣고 있고 Google은 안 넣고 있는 것으로 보입니다.

https://github.com/femiwiki/infra/blob/49c5995cac9a4dcf800e288296793d96ad963be5/aws/route53.tf#L38-L45

**Comment by lens0021** [comment]
@revi 님 혹시 G suite 설정 한번 시도해주실수 있나요? 제가 하려니까 모르는게 영 많아서 아리송하네요 ㅠ

**Comment by revi** [comment]
SPF 설정 됐고, DKIM 설정 됐고 (실제로 DKIM 서명이 된 이메일이 발송되는지는 헤더를 까서 검증해보긴 해야 하겠습니다만) 일단 DMARC p=none (보고서만 받기)로 하나쯤 받아봐도 될 거 같긴 하네요.

**Comment by revi** [comment]
DMARC 원본 파일 (XML 파일 투성이) 을 구글 MS fastmail.com 등등으로부터 매번 받을 만한 이유는 없는 거 같아서 https://dmarc.postmarkapp.com 으로 요약본만 받아보도록 세팅할 예정입니다 (나중에 필요하면 우리 주소 넣어도 됨).

**Comment by revi** [comment]
![image](https://github.com/femiwiki/femiwiki/assets/7630875/6241f135-fd78-4165-8293-37f18a13dae8)

따봉입니다
