### ISSUE TITLE
검색엔진 애널리틱스 점검

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#173]
TBD

- [x] 구글
- [x] 빙
- [x] [네이버](https://searchadvisor.naver.com/)
- [ ] Yandex (Duckduckgo)

**Comment by revi** [comment]
* 네이버는 2개 이상 계정 추가할 수 있는지 여부 불확실
* 빙은 [가능](https://www.bing.com/webmaster/help/how-to-add-users-to-your-site-account-d5c00364)
* 구글은 당연히 됨

**Comment by lens0021** [comment]
![image](https://user-images.githubusercontent.com/28209361/75627017-d968a480-5c0f-11ea-9e4e-2542ceea5e55.png)


위는 검색엔진 사용량 참고용으로 최근 3개월 통계입니다.

**Comment by revi** [comment]
[Google Search Engine Console](https://search.google.com/search-console) 소유자 (최고) 권한은 `admin@femiwiki.com` 계정이 가지는 게 맞겠죠? [도움말](https://support.google.com/webmasters/answer/34592?hl=ko) 따라서 소유자 인증 해 주시면 될 것 같어요.

**Comment by revi** [comment]
> [Google Search Engine Console](https://search.google.com/search-console) 소유자 (최고) 권한은 `admin@femiwiki.com` 계정이 가지는 게 맞겠죠? [도움말](https://support.google.com/webmasters/answer/34592?hl=ko) 따라서 소유자 인증 해 주시면 될 것 같어요.

아마 도메인 속성을 먼저 인증하면 `https://femiwiki.com` URL 접두사 속성은 도메인 속성 인증 상속돼서 자동 인증 처리 될 거예요.

그다음에 사이드바 왼쪽 설정 > 사용자 및 권한 > 소유자 오른 쪽의 점 세개 클릭 > 속성 소유자 관리 에서 속성 소유자 추가할 수 있습니다.

**Comment by lens0021** [comment]
Google Search Console에 @revi @simnalamburt @love-adela @miriryu 님+저까지 추가하고, [구글시트](https://docs.google.com/spreadsheets/d/1FZXbegisPQm7gGhalZ6hy45WQQphv25K5fKdjC08WLE) 업데이트했습니다 https://search.google.com/search-console 에서 접속 가능합니다~

**Comment by love-adela** [comment]
감사합니다!

**Comment by revi** [comment]
네이버 아이디는 휴대전화 인증을 해야 해서 계정은 기존에 사용하던 번호 이용해서 생성 요청하고 -> 생성된 계정으로 네이버 애널리틱스 인증만 진행해서 추가하려고요.

**Comment by lens0021** [comment]
https://femiwiki.com/naver2e986bb58727091ba14461e6215367f0.html 변경되었습니다~ @revi

**Comment by revi** [comment]
<img width="80%" alt="image" src="https://user-images.githubusercontent.com/7630875/86498038-0c3dc780-bdbf-11ea-9e8c-eda3cf747b70.png">

👍 

Robots.txt 에 있는 `https://femiwiki.com/sitemap/sitemap-index-femiwiki.xml` 주소가 404 Not Found라고 뜨는데, 수정이 필요한 부분일까요?

**Comment by revi** [comment]
네이버 애널리틱스 제출했습니당.

<img width="80%" alt="image" src="https://user-images.githubusercontent.com/7630875/86926281-d5740280-c16c-11ea-9a03-6e0a85795ddb.png">

그나저나 네이버가 뭔가 불만이 많은 모양이에요.

![image](https://user-images.githubusercontent.com/7630875/86926500-1b30cb00-c16d-11ea-9806-7cb9bf64651c.png)

**Comment by lens0021** [comment]
og는 [OpenGraphMeta](https://www.mediawiki.org/wiki/Extension:OpenGraphMeta)에서 제공해주는데 아마 사이트맵 깨져있는 것 때문에 저리 뜨는게 아닐까 한번 추측해봅니다...

**Comment by lens0021** [comment]
Yandex 추가했고 페미위키 구글 계정으로 접근할 수 있습니다. https://webmaster.yandex.com/site/https:femiwiki.com:443/dashboard/
