### ISSUE TITLE
대문에 페이팔 이외의 기부 수단 안내하기

### ISSUE THREAD

**Issue by simnalamburt** [femiwiki/femiwiki#175]
기부수단을 여러개 세팅했다. 대문에 써놓자

- [x] 페이팔
- [x] Buy Me A Coffee
- [x] Patreon
- [x] 포스타입
- [ ] Open Collective (아직 계정 세팅 안됨)
- [ ] 비트코인, 이더리움, 등 가상화폐 지갑 (아직 계정 세팅 안됨)
- [ ] [MRM](http://www.humansoftware.co.kr/sub1/doc1_1.asp?doc_subpage=1) 혹은 효성CMS (아직 계정 세팅 안됨)
- ~~GitHub Sponsors~~ 비영리사단법인 등록 혹은 비영리임의단체 지정 필요함
- ~~네이버 해피빈~~ 상근자 있는 단체만 신청 가능

**Comment by lens0021** [comment]
링크 적어놓습니다.

**Comment by lens0021** [comment]
[페미위키:후원 안내](https://femiwiki.com/w/%ED%8E%98%EB%AF%B8%EC%9C%84%ED%82%A4:%ED%9B%84%EC%9B%90_%EC%95%88%EB%82%B4) 이외에
[페미위키:대문/후원](https://femiwiki.com/w/%ED%8E%98%EB%AF%B8%EC%9C%84%ED%82%A4:%EB%8C%80%EB%AC%B8/%ED%9B%84%EC%9B%90)에도 수정해주실 수 있나요? 이쪽이 진짜 대문에 표시되는 쪽입니다.

**Comment by simnalamburt** [comment]
현재 "페미위키:후원 안내" 문서 한국어와 일본어 페이지에 설명 들어감

**Comment by simnalamburt** [comment]
대문 한국어/영어 링크

- https://femiwiki.com/w/%ED%8E%98%EB%AF%B8%EC%9C%84%ED%82%A4:%EB%8C%80%EB%AC%B8/%ED%9B%84%EC%9B%90/ko
- https://femiwiki.com/w/%ED%8E%98%EB%AF%B8%EC%9C%84%ED%82%A4:%EB%8C%80%EB%AC%B8/%ED%9B%84%EC%9B%90/en

후원 안내 문서 한국어/일어 링크

- https://femiwiki.com/w/%ED%8E%98%EB%AF%B8%EC%9C%84%ED%82%A4:%ED%9B%84%EC%9B%90_%EC%95%88%EB%82%B4/ko
- https://femiwiki.com/w/%ED%8E%98%EB%AF%B8%EC%9C%84%ED%82%A4:%ED%9B%84%EC%9B%90_%EC%95%88%EB%82%B4/ja

**Comment by simnalamburt** [comment]
계정 세팅 다 된것들은 일단 대문에 다 올라갔으니, 마일스톤에선 제외하곘습니다
