### ISSUE TITLE
확장기능들 .github/workflows/rebuild-docker-mediawiki.yml 고치기

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#178]
- `commits_url` 삭제하기
- 처음에 만들 땐 rebuild가 목적이었지만 현재는 아니므로 dispatch-to-docker-mediawiki든 뭐든가로 고치기

----

- [x]  https://github.com/femiwiki/FemiwikiSkin
- [x]  https://github.com/femiwiki/UnifiedExtensionForFemiwiki
- [x]  https://github.com/femiwiki/FacetedCategory
- [x]  https://github.com/femiwiki/CategoryIntersectionSearch

**Comment by simnalamburt** [comment]
"Submit a PR to docker-mediawiki repository" 로 통일할게요

**Comment by simnalamburt** [comment]
Jobs Done

**Comment by simnalamburt** [comment]
파일 이름을 안바꿨는데 "submit-patch.yml" 로 통일할게요
