### ISSUE TITLE
Modify the image tag format "docker-mediawiki"

### ISSUE THREAD

**Issue by love-adela** [femiwiki/femiwiki#179]
날짜 + SHA로 되어 있던 것 '-' 기호 넣고 ISO8601 형식 준수해서 태깅하도록 수정하기.

**Comment by lens0021** [comment]
액션에서 태그 붙이는 부분입니다: https://github.com/elgohr/Publish-Docker-Github-Action/blob/a11682167c13d44d09d44a8c601c435e6372d8c9/entrypoint.sh#L133-L135

**Comment by lens0021** [comment]
저번에 제가 액션 떼면서 해서 이 이슈가

https://github.com/femiwiki/docker-mediawiki/blob/d53575c/.github/workflows/test-and-publish.yml#L40:
> `- run: echo "::set-output name=tag::$(date +%Y%m%d%H%M%S)$(echo ${{ github.sha }} | cut -c1-6)"`

위 한 줄을 고치면 되는 심하게 간단한 작업으로 변모하였습니다. 거의 폰으로 깃헙에서 바로 고쳐도 될 수준이오니 @love-adela 께서는 참고하여 주시기 바랍니다
