### ISSUE TITLE
Extension:DiscussionTools

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#196]
https://mediawiki.org/wiki/Extension:DiscussionTools

**Comment by love-adela** [comment]
이건 어떤 이슈인가욤?

**Comment by lens0021** [comment]
미디어위키의 토론 시스템은

1. 일반 문서에 편집자들이 각자 자기 의견을 달고 그 뒤에 자기 이름을 다는 방식
2. 게시판처럼 보이도록 현대적으로 새로 만들어진 방식

이 두 가지가 있는데 위키백과에서 2번을 널리 보급하는 데 실패하였고, 그냥 1번을 강화하기 위한 확장기능을 만들었는데 이것이 DiscussionTools입니다.
저희는 2번을 쓰고 있기는 한데 1번도 적용하면 좋을 것 같아 만든 이슈입니다. 적용만 하면 될 것으로 예상됩니다.

**Comment by lens0021** [comment]
확인해보니 릴리즈 전이어서 Blocked로 옮깁니다
