### ISSUE TITLE
[Safari] '바뀐글' 페이지, 문서 페이지에 들어온 상태에서 햄버거버튼을 눌러도 메뉴가 노출되지 않는 현상

### ISSUE THREAD

**Issue by Larodi** [femiwiki/femiwiki#198]
바뀐글, 문서 등 메인 외 페이지들에 진입해있는 상태에서 햄버거버튼을 눌러도 메뉴가 노출되지 않음.
페미위키 대문 페이지에서는 정상적으로 작동됨.

**Comment by lens0021** [comment]
(제가 사파리가 없어서)같은 엔진을 쓰는 [GNOME Web](https://wiki.gnome.org/Apps/Web)으로 해봤을 때는 재연이 안 됩니다. [브라우저의 콘솔 메뉴](https://support.apple.com/ko-kr/guide/safari/sfri20948/mac)가 열린 채로 햄버거 메뉴가 안 눌리는 상태를 만들어서 콘솔에 내용이 뜨는지 확인해 주실 수 있나요?

**Comment by lens0021** [comment]
우선 https://github.com/femiwiki/FemiwikiSkin/issues/146 을 진행하면 단기적인 해결이 되므로 진행하고 있겠습니다

**Comment by lens0021** [comment]
아마 이제 괜찮아졌을텐데 아니면 여기 남겨주세요~
