### ISSUE TITLE
사이트맵 사라짐

### ISSUE THREAD

**Issue by revi** [femiwiki/femiwiki#205]
참조: #173

[robots.txt](https://femiwiki.com/robots.txt) 에서 `sitemap:` 구문의 파일이 존재하지 않습니다. 아래 구글 스크린샷을 참조하면 과거에는 존재했던 기록이 있는데, 구글에서도 현재 "Couldn't fetch" 라고 표시하고 있는 것으로 보아 무언가 작업 중 유실된 듯 합니다. 스크린샷 URL도 약간 이상하긴 하네요. `https://femiwiki.com/https://femiwiki.com/sitemap/sitemap-femiwiki-NS_0-0.xml` ("`https://femiwiki.com/`"이 두 번 들어갑니다.)

<img width="80%" alt="image" src="https://user-images.githubusercontent.com/7630875/86498313-46f42f80-bdc0-11ea-9721-bc829659eb91.png">

**Comment by revi** [comment]
재생성 확인했습니다. 닫을게요.

<img width="60%" alt="image" src="https://user-images.githubusercontent.com/7630875/86926040-8d54e000-c16c-11ea-98ec-e3f1ab66d236.png">

**Comment by lens0021** [comment]
어 아직 그대론데...네... 좋아요 그럴수있조

**Comment by simnalamburt** [comment]
다시 고장남

**Comment by lens0021** [comment]
디스코드 \#개발팀 채널
```
lens0021 — 01/20/2021
사이트맵 혹시 http랑 fastcgi랑 분리하면서 기존 사이트맵 생성 cron이 fastcgi쪽으로 가고 캐디는 static을 자기 볼륨에서 찾아서 망한거 아닐까 싶어버리네요,,허허,,

simnalamburt — 01/21/2021
@Lens0021 사이트맵 그거 그러면 딱 그 경로만 fastcgi로 넘어가도록 하드코딩하면 될라나요?

lens0021 — 01/20/2021
사이트맵... 어떻게 하신다는 것인지 잘 모르겠지만 되면 되는거죠 머 하핫
```

**Comment by lens0021** [comment]
호스트볼륨...쓰기엔 호스트볼륨이 그렇게 좋은것도 아니고 (설정 바꿀때마다 노매드 대몬 껐다 켜야하고 나중에 클러스터링할거면 곤란) CSI는 아직 좀 불안해서 (한동안 해시코프에 티켓 좀 많이 쏴야할거같음) 도커 볼륨으로 공유하는 게 되면 그렇게 해보겠습니다

**Comment by lens0021** [comment]
글고보니 이유는 검색했더니 그냥 볼륨 공유하래서..입니다 https://serverfault.com/questions/805169/is-it-possible-to-serve-static-html-from-php-fpm

**Comment by lens0021** [comment]
cron의 로그를 확인하려고 했더니 로그가 없어서... 직접 `/usr/local/bin/generate-sitemap >> /tmp/log/cron.log 2>&1`실행해보니
"bash: /tmp/log/cron.log: No such file or directory"라고 나와서 고쳤습니다. &rarr; https://github.com/femiwiki/docker-mediawiki/commit/7a8f559c1eb80ab7b961f8c5aa01ce5779df48ad

**Comment by lens0021** [comment]
서버에서도 되는가 시험해보려고 실행했는데 잘 되어서... femiwiki.com/sitemap/sitemap-index-femiwiki.xml 가 살아났구요, 도커 볼륨이다 보니까 도커 볼륨 지우지 않는 한 계속 있을 예정입니다.
