### ISSUE TITLE
페미위키 개발팀 3분기 OKR 설정하기

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#207]
TBD.

<details>
<summary>지난 목표들</summary>

| 시기 | O | KR |
|--|--|--|
| 2019년 4분기 | ? | 월고정비 8만원 |
| 2020년 1분기 | 지속 가능한 위키 | 손으로 배포해야 하는 repository 3개 이하 |
| 2020년 2분기 | 프론트엔드 갈아엎기 | PHP와 HTML 코드가 붙어 있는 문제 해결 |
</details>

**Comment by simnalamburt** [comment]
ㅎ허헣 2020년 2분기는 개발자가 둘이나 학교로 가버려서 대차게 사라진것같군요,,

**Comment by lens0021** [comment]
8월 말에 있을 운영팀 전체회의 전까지 각 팀 OKR 정하기로 되었습니다~🎉

개인적으로 하고 싶은 일은 위키베이스와 위키데이터 브릿지를 사용이 편리하도록 설정하여 실제 편집자들에게 부담없이 권할 수 있는 수준까지 만드는 것이고...(현재는 사용에 불편이 있는 것 같습니다 아무도 안 쓰는 걸 보니까..)

저희 위키에 필요한 것을 고려한다면 튜토리얼 만들기나 도전과제 뱃지 확장 기능 만들기를 목표로 하는 게 좋을 것 같습니다.

각자 생각하시는 목표 달아주세요~

**Comment by simnalamburt** [comment]
전 3분기엔 적극적으로 참여하기는 조금 어려울 것 같습니다. 활동하실분들이 하시고싶은것 위주로 정하시는게 맞을 것 같아요

**Comment by simnalamburt** [comment]
O: 업그레이드 하다 만 인프라 정리하기
KR: https://github.com/femiwiki/femiwiki/issues/116 닫기
