### ISSUE TITLE
Cache anonymous request

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#219]
![image](https://user-images.githubusercontent.com/28209361/103166610-3b615d00-4867-11eb-8dbc-c318ace3dfae.png)

![image](https://user-images.githubusercontent.com/28209361/103166618-46b48880-4867-11eb-8fab-4eb53ed64ee9.png)

~~한국시간~~ 23일 15시 이후로 CPU가 많이 사용되는 빈도가 확연하게 늘어 원인 파악이 필요합니다.

아이고 잘못적었네 23일 15시는 UTC이고 한국시간은 아래 참고해주세요
한국 시간 05시는 데이터베이스 백업 크론 도는 시간입니다.
그다음부터를 증상이 나타난 걸로 보면 한국시간 23일 09:10부터입니다

![image](https://user-images.githubusercontent.com/28209361/103166805-ffc79280-4868-11eb-89d6-62410ad735d2.png)

**Comment by simnalamburt** [comment]
그냥 저때에 익명 리퀘스트가 많이 들어왔다. 익명 리퀘스트에 캐싱 레이어를 넣어보자

##### Reference
- https://www.mediawiki.org/wiki/Manual:Cache
- https://www.mediawiki.org/wiki/Manual:Configuration_settings#Cache
- https://www.mediawiki.org/wiki/Manual:Caching
- https://www.mediawiki.org/wiki/Manual:Performance_tuning
- https://varnish-cache.org/
- https://github.com/caddyserver/cache-handler

**Comment by lens0021** [comment]
### [중간 메모]

Varnish는 캐시 백엔드로 malloc, umem, file을 제공하며 기본값은 가능하면 umem, 아니면 malloc입니다.[1]
Varnish docker image[2]는 환경 변수 `VARNISH_SIZE`로 백엔드 사이즈 제한을 설정할 수 있습니다.[3]
미디어위키는 캐시 purge가 필요한 시점에 `$wgCdnServers`[4]로 설정된 서버들에 `PURGE` 명령을 내립니다.
VCL을 통해 로그인 유저의 리퀘스트는 무시하도록[5] 할 수 있습니다.
위키미디어의 vcl파일들은 [wikimedia/puppet](https://github.com/wikimedia/puppet) 리포지토리의 `/modules/varnish/templates/`에 ERB(embedded Ruby template syntax)[6] 파일들로 저장되어 있습니다.

- [wikimedia-frontend.vcl.erb](https://github.com/wikimedia/puppet/blob/120dff458fea24318bbcb31b457b5b7d113e66a9/modules/varnish/templates/wikimedia-frontend.vcl.erb) - common frontend code for all clusters
- [misc-frontend.inc.vcl.erb](https://github.com/wikimedia/puppet/blob/120dff458fea24318bbcb31b457b5b7d113e66a9/modules/varnish/templates/misc-frontend.inc.vcl.erb)

misc-frontend.inc.vcl.erb에는 쿠키를 확인해서 캐싱을 무시하는 구문도 있는데,[7] 주석에 따르면 다음을 검사합니다.

> google analytics cookies and our own global WMF-Last-Access,[8] WMF-Last-Access-Global GeoIP, and CP cookies

(저희는 나중에 여유되면 ga만 쓰든가 아님 말든가...)

[1] https://varnish-cache.org/docs/trunk/users-guide/storage-backends.html
[2] https://hub.docker.com/_/varnish/
[3] https://github.com/varnish/docker-varnish/blob/c0846f15/fresh/debian/docker-varnish-entrypoint#L14
[4] https://www.mediawiki.org/wiki/Manual:$wgCdnServers
[5] https://github.com/wikimedia/puppet/blob/120dff458fea24318bbcb31b457b5b7d113e66a9/modules/varnish/templates/misc-frontend.inc.vcl.erb#L36-L39
[6] https://puppet.com/docs/puppet/5.5/lang_template_erb.html
[7] https://github.com/wikimedia/puppet/blob/120dff458fea24318bbcb31b457b5b7d113e66a9/modules/varnish/templates/misc-frontend.inc.vcl.erb#L41-L49
[8] https://wikitech.wikimedia.org/wiki/Analytics/Data_Lake/Traffic/Unique_Devices/Last_access_solution

**Comment by simnalamburt** [comment]
[caddy-wmcache](https://github.com/femiwiki/caddy-wmcache)를 만들기 시작했는데, "특수:내언어"를 쓰지 않으면 충분히 빠르다는 사실 발견함. 어쩌면 "특수:내언어"를 최적화하거나 캐싱하기만 해도 이 문제가 해결될지도 모른다.

**Comment by lens0021** [comment]
FYI: MW 1.35는 php-curl이 있을 때 PURGE request를 못 보내는 버그가 있다는 것 같습니다 https://phabricator.wikimedia.org/T264735

**Comment by lens0021** [comment]
기본적인 건 거의 다 구현한 거 같은데, 미디어위키에서 공식적으로 캐시 스펙을 문서화한 게 없어서 대충 코드 보면서 맞췄습니다.
그래서 웬만한 건 다 괜찮은데 하나 제일 모르겠는 게...

`s-maxage`가 정해져 있는 response를 캐시에 넣었다가 꺼낼 때 ... 뭐랑 비교해서 상했는지를 알 수 있는 거죠...? 비교할 절대적인 시간 정보가 없어서 그냥 따로 Date 이름으로 헤더를 현재 시간으로 저장하도록 해봤는데... 이게 맞는 건지... 어쩐 건지.. 돌아가긴 잘 돌아가는데 미디어위키에서 Date를 따로 안 써주는 거 같아서.. 이상하고... 근데 www.mediawiki.org 같은 곳은 Date 헤더가 있더라구요 어디서 추가된 건지...

**Comment by lens0021** [comment]
Blocked by https://github.com/femiwiki/femiwiki/issues/239
