### ISSUE TITLE
Saving Plan 구입하기

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#246]
t4g 구입

**Comment by simnalamburt** [comment]
이거 못사고 있었던 이유가 머였죵

**Comment by lens0021** [comment]
저희가 내는 요금이 너무 쬐끄매서 Commitment 자동 추산이 안 되고 직접 계산해야 하는데, 결정적인 건 아니고 그냥 이리저리 밀리다 보니 안 했습니다

**Comment by simnalamburt** [comment]
EC2 Instance Saving Plan, 1 year, ap-northeast-1, t4g, 0.013 USD, All Upfront 로 실행함

**Comment by simnalamburt** [comment]
Active 된것 확인, Closing
