### ISSUE TITLE
Add branches for REL1_37

### ISSUE THREAD

**Issue by RhinosF1** [femiwiki/femiwiki#286]
ToDo list (All extensions of FemiWiki):

- [x]  AchievementBadges
- [x]  DiscordNotifications
- [x]  FacetedCategory
- [x]  FemiwikiSkin
- [x]  Sanctions
- [x]  UnifiedExtensionForFemiwiki

Was cut yesterday @lens0021

**Comment by lens0021** [comment]
Done. thank you!
