### ISSUE TITLE
페미위키 배포 자동화

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#3]
[CD](https://github.com/femiwiki/femiwiki/issues/4) = 배포자동화 = Spot Fleet을 사용한 비용절감 = [Autoscale을 사용한 사이트 안정화](https://github.com/femiwiki/femiwiki/issues/2)

네개가 사실상 모두 같은 이슈임

### Activity
- Hyeon Kim added [this card](https://trello.com/c/eyiuQ2dF) to 작업중 - Dec 24 at 12:43 PM
- Hyeon Kim joined this card - Dec 24 at 12:43 PM

**Comment by simnalamburt** [comment]
Close as duplicate of https://github.com/femiwiki/femiwiki/issues/4
