### ISSUE TITLE
변경사항 어딘가에 공지로 남기든 문서화하든 기록하기

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#41]
고생한거 누락되지 않도록 공지 쓰기

#### 기록 공간

- [CHANGELOG.md](https://github.com/femiwiki/femiwiki/blob/master/CHANGELOG.md) on Github
- [페미위키 안에 만든 미니 블로그 (CC BY-SA 4.0)](https://femiwiki.com/w/%ED%8E%98%EB%AF%B8%EC%9C%84%ED%82%A4:%EA%B0%9C%EB%B0%9C_%EB%B8%94%EB%A1%9C%EA%B7%B8)  ~~CC BY-SA 4.0으로 글 쓰면 김젼 개인블로그에도 복붙할수있지롱~~
- [페미위키:업데이트](https://femiwiki.com/w/%ED%8E%98%EB%AF%B8%EC%9C%84%ED%82%A4:%EC%97%85%EB%8D%B0%EC%9D%B4%ED%8A%B8)
- [페미위키:공지사항](https://femiwiki.com/w/%ED%8E%98%EB%AF%B8%EC%9C%84%ED%82%A4:%EA%B3%B5%EC%A7%80%EC%82%AC%ED%95%AD)

#### 문서화할것 목록
- [ ] [https://github.com/femiwiki/mediawiki/labels/글쓰기](https://github.com/femiwiki/mediawiki/issues?utf8=%E2%9C%93&q=label%3A%EA%B8%80%EC%93%B0%EA%B8%B0+)
- [ ] [https://github.com/femiwiki/femiwiki/labels/글쓰기](https://github.com/femiwiki/femiwiki/issues?utf8=%E2%9C%93&q=label%3A%EA%B8%80%EC%93%B0%EA%B8%B0+)
- [x] https://femiwiki.com/w/%EC%A3%BC%EC%A0%9C:Tucnhru6s1xg3fo7 &rarr; [페미위키:개발 블로그/1](https://femiwiki.com/w/%ED%8E%98%EB%AF%B8%EC%9C%84%ED%82%A4:%EA%B0%9C%EB%B0%9C_%EB%B8%94%EB%A1%9C%EA%B7%B8/1)
- [x] 2017-07-15 https://femiwiki.com/w/%EC%A3%BC%EC%A0%9C:Tucnhru6s1xg3fo7
- [x] ~~2018-03-28 https://femiwiki.com/w/%EC%A3%BC%EC%A0%9C:Ua328560cx3wlwyf~~ 대부분 중복
- [x] 2018-03-29 https://femiwiki.com/w/%EC%A3%BC%EC%A0%9C:Ua9cr7vmr6inj387
- [x] 2018-04-xx https://docs.google.com/presentation/d/1Q1eKcC1fgit52lpDbr5dTaoHZw2xTjANr1e87k58-kE/edit
- 2018-04-29: 테스트서버 가동
- [x] 2018-05-08: https://femiwiki.com/w/%EC%A3%BC%EC%A0%9C:Ucqjvynmqbox0jyv 이 기능 추가했다가 js 지원 끊어져서 사라짐 -낙엽
- 2018-09-05 https://github.com/femiwiki/skin/issues/60

#### Activity
- Hyeon Kim added [this card](https://trello.com/c/PI0gzqY2) to Backlog - Sep 15, 2018 at 9:26 PM
- Hyeon Kim moved this card from Backlog to 작업중 - Oct 7, 2018 at 4:22 AM
- Hyeon Kim moved this card from 작업중 to Backlog - Oct 7, 2018 at 4:30 AM
- 낙엽 Dec 22, 2018 at 2:51 PM
  > "페미위키:기술 블로그" 이런 이름으로 문서를 만들어볼까요?

**Comment by simnalamburt** [comment]
https://github.com/femiwiki/femiwiki 이 리포에 CHANGELOG.md 를 만들어서 일단 자잘한건 거기에다가 기록하고 페미위키에 공지할만한 변화나 점검같은거만 페미위키 내 문서에 공지로 띄우기로 결정됨

**Comment by lens0021** [comment]
혹시 이거 시간순으로 적으면 되나요 아니면 역시간순으로 적으면 되나요?

**Comment by simnalamburt** [comment]
최신 수정사항일수록 위로오게 써주시는게 나을거같네요

**Comment by lens0021** [comment]
이 이슈는 완료되었는지 판단하기에 너무 포괄적입니다~ 목록 중 많은 부분이 달성되었으므로 닫습니다
