### ISSUE TITLE
`simnalamburt+femiwikilogo@gmail.com` 를 페미위키 공식 이메일로 바꾸기

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#48]
도커헙에 `simnalamburt+femiwikilogo@gmail.com` 라는 이메일이 gravatar 이메일로 등록되어있는데, 김지현의 개인 계정임. 페미위키 공식이메일로 바꾸기.

#### Activity

- Hyeon Kim added [this card](https://trello.com/c/UxGAntNz) to Backlog - Jan 3 at 1:07 PM

**Comment by simnalamburt** [comment]
도커헙이 업데이트되면서 Gravatar 계정을 안만들어도 도커헙에 프로필 사진을 달 수 있게 되었다.

**Comment by simnalamburt** [comment]
Gravatar 쓰려면 워드프레스 계정이 있어야한다. 계정이 늘면 관리하기 귀찮아지므로, 슬프지만 프로필사진을 포기한다.
