### ISSUE TITLE
RESTBase를 여럿 운용 가능한지 테스트

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#52]
> **서버가 여럿일 때 정상 작동하는지 확인**을 위해 시험삼아 Docker compose에서 RESTBase의 replicas를 2로 올려봤는데 시각편집기에서 원본편집으로 전환할때 간헐적으로 `apierror-visualeditor-docserver-http` 오류가 납니다.
 https://github.com/femiwiki/femiwiki/issues/47#issuecomment-459960415

제가 위와 같이 적었는데, replicas가 2 이상이었다는 건 해당 콘테이너의 포트가 따로 안 열려 있었던 것으로 생각됩니다, 제대로 시험되지 않은 것으로 보고 다시 해보고 가능하면 수정해야겠습니다.

**Comment by lens0021** [comment]
config.yaml의 table 아래의 configuration: https://www.npmjs.com/package/restbase-mod-table-cassandra#configuration

**Comment by lens0021** [comment]
#### TODO

- [ ] RESTBase의 데이터를 날릴 때 영향 명시된 것 있나 찾아보기
- [ ] 카산드라 비밀번호 등

#### 점검 시나리오

(TODO)

**Comment by simnalamburt** [comment]
TODO에 있는 밑에 두개는 해결된건가요?

- RESTBase의 데이터를 날릴 때 영향 명시된 것 있나 찾아보기
- 백업과 복구 방법 알아보기

**Comment by lens0021** [comment]
https://github.com/femiwiki/femiwiki/issues/57 으로 생성되었습니다.
