### ISSUE TITLE
Node 서비스들을 AWS Lambda로 돌리기

### ISSUE THREAD

**Issue by simnalamburt** [femiwiki/femiwiki#53]
https://github.com/awslabs/aws-serverless-express 이걸로 가능할듯

**Comment by lens0021** [comment]
RESTBase는 캐시이기 때문에 적절하지 않고, Parsoid도 위키에서 정보를 받아서 저장해 놓는 부분이 있어서[1] 그거만 어디 저장하든지 아님 모든 리퀘에서 저 부분을 반복하든지 해야할 것 같고, 일단 시범삼아 해본다면 Mathoid가 진짜 위키랑 별 상관도 없고 stateless해서 얘를 제일 먼저하는 게 좋을 것 같습니다. 

1: https://github.com/wikimedia/parsoid/blob/master/tools/sync-baseconfig.js

**Comment by lens0021** [comment]
Parsoid.js와 RESTBase[1]는 위키미디어 재단에서 선셋하고 있어서 사라졌고
Mathoid[2]도 선셋 예정이라고 해서 위키미디어에 기생하는 걸로 바꿨습니다.
닫습니다.

1: https://www.mediawiki.org/wiki/Core_Platform_Team/Initiatives/Sunsetting_RESTBase
2: https://github.com/femiwiki/docker-mediawiki/issues/690
