### ISSUE TITLE
Automatically version docker images

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#56]
> - `femiwiki/mediawiki:build-123`
> - `femiwiki/mediawiki:release-123`
> 
> 둘중 하나 쓰면 될거같아요. 당분간은 `femiwiki/mediawiki:build-123` 쓰고, 나중에 CI/CD 자동화가 되면 `femiwiki/mediawiki:release-123` 로 옮길까 싶네요.

- https://github.com/femiwiki/mediawiki/pull/257#discussion_r256226026

#### 자동 버저닝 TODOs

- [x] ?

#### 수동 버저닝 TODOs

- [x] 도커 클라우드에 빌드 룰로 다음 생성
```
Source Type: Tag
Source: /^build-[0-9]+$/
Docker Tag: {sourceref}
```
이때 `https://cloud.docker.com/u/femiwiki/repository/docker/femiwiki/이름/hubbuilds` url로 클래식 오토 빌드가 활성화되어 있는 경우는 비활성화하고 `https://cloud.docker.com/u/femiwiki/repository/docker/femiwiki/이름/builds/edit` 로 새 오토 빌드를 활성화
- [x] 기존 도커 이미지들에 `build-0` 태그 붙이기(femiwiki/cassandra와 femiwiki/mediawiki는 제외됨)
- [x] femiwiki/mediawiki가 사용하는 다른 도커 이미지들 준비될 때까지 기다리기 or 준비 시키기(직접 빌드하고 이미지 푸시하든가...)
- [x] 소스코드에 태그 붙이기(도커 컴포즈 파일, 도커파일)
  - [x] femiwiki/mediawiki
  - [x] femiwiki/database
- [x] 카산드라를 어떻게 하기 &rarr; https://github.com/femiwiki/femiwiki/issues/52 진행할 때 `build-0`으로 릴리즈 하나 만들기

**Comment by simnalamburt** [comment]
Blocked by https://github.com/femiwiki/femiwiki/issues/51

**Comment by lens0021** [comment]
> simnalamburt님(2020-02-02 18:26+0900 https://discordapp.com/channels/314953743185477644/566264019409698817/673459239225917469):
Travis에선 자동버저닝 하는법을 아는데
Travis에선 그냥 TRAVIS_BUILD_NO 이런식의 환경변수가 있어서
거기에 트래비스 빌드번호가 입력되거든요
그래서 걍 docker tag femiwiki/mediawiki:blabla-${TRAVIS_BUILD_NO} 이러면 돼요
GitHub Actions는 아직 안알아봤는데 비슷한게 있을거에요

관련해서 검색해 봤는데 아래 게시물을 찾았습니다:
https://github.community/t5/GitHub-Actions/Getting-the-run-id-of-a-run-in-Github-Actions/td-p/36567

아마 `TRAVIS_BUILD_NO`의 아주 정확한 대체제는 아직 없는 것 같습니다.?

**Comment by lens0021** [comment]
도커 빌드에 사용하게 될 [Publish Docker GitHub Action](https://github.com/marketplace/actions/publish-docker)에 `{YEAR}{MONTH}{DAY}{HOUR}{MINUTE}{SECOND}{first 6 digits of the git sha}`으로 태그를 붙이는 기능이 있어 그걸 사용하게 될 것 같습니다.
