### ISSUE TITLE
볼륨 입출력 줄이기

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#64]
![image](https://user-images.githubusercontent.com/28209361/54792195-72611280-4c80-11e9-803c-55293dda476b.png)

UTC 2월 2일 17시부터 EBS:VolumeIOUsage이 발생, UTC 2월 14일 20시와 UTC 3월 8일 21시에도 증가한 것 같음.
(KST로는 각각 2월 3일 04시, 2월 15일 05시, 3월 9일 06시)

- 백업봇 파일 쓰기 줄이기
  - [x] 코드 수정 &rarr; https://github.com/femiwiki/backupbot/commit/fd6c73a31e8f58f62275bc141643fbbfdfc71fd0
  - [x] backupbot 새 빌드 릴리즈
  - [x] 도커 클라우드에 이미지 직접 푸시
  - [x] femiwiki/database 빌드 태그 증가
  - [x] 서버에서 git pull
  - [x] 서버에서 도커 디플로이
  - [x] 3월 11일 백업 잘 되었는지 확인 &rarr; https://s3.console.aws.amazon.com/s3/buckets/femiwiki-backups/?region=ap-northeast-1&tab=overview
  - [x] AWS 콘솔에서 볼륨 입출력 얼마로 나왔나도 확인 &rarr; 변화없음
  - [x] 백업 2일에 한 번으로 줄임 &rarr; https://github.com/femiwiki/backupbot/commit/d0866b6f1078b6f0a87b31a2fca1903c72e9d5ef &rarr; 3월 18일 백업이 생략된 걸 시작으로 이틀에 한 번으로 줄어듦
  - [x] 입출력 확인 &rarr; 그냥 그럼
- [모니터링 프로그램써서 io 발생시키는 원인 추적하기](https://discordapp.com/channels/314953743185477644/341920917556953089/558095508602748929)
  - [x] atop 설치 &rarr; `sudo yum install 'https://www.atoptool.nl/download/atop-2.4.0-1.x86_64.rpm'`
  - [x] atop 수집결과 확인
  - [x] ~~atop 삭제 &rarr; `sudo yum autoremove atop`~~ 삭제 안하고 계속 둘거임 https://github.com/femiwiki/femiwiki/issues/64#issuecomment-489976867
- 카산드라 최적화
  - [x] 카산드라 하드디스크 사용량 확인
  - [x] ~~카산드라 최적화 하기~~ EBS 타입을 standard에서 gp2로 바꾸기로 결정하면서 할 필요가 없어졌음 https://github.com/femiwiki/femiwiki/issues/64#issuecomment-489976867

**Comment by lens0021** [comment]
[Iotop](http://guichaz.free.fr/iotop/)라는 얘가 있다네요...

**Comment by simnalamburt** [comment]
근데 저희가 iotop을 48시간동안 켜놓고 쳐다볼수는 없으니 긴 시간동안 돌려주고 프로세스별 사용량 총합 구해주는 보고서를 뽑을 수 있어야해요. iotop에 그런 기능이 있는지 알아봐주거나 그런일을 하는 오픈소스 프로그램이나 무료서비스를 찾아야할거같아요

**Comment by simnalamburt** [comment]
atop이 적당해보이네요

https://www.atoptool.nl/
https://serverfault.com/a/729490

**Comment by lens0021** [comment]
[man-page](https://linux.die.net/man/1/atop)에서 당장 쓸모 있어 보이는 사용법만 찾아봤습니다.

우선 atop은 설치되는 시점부터 `/usr/share/atop`라는 디렉토리에 `atop.daily`라는 스크립트를 저장하고, 이 스크립트는 atop을 주기적으로(기본값은 10분) 실행하여 `/var/log/atop/atop_YYYYMMDD`라는 raw 파일을 저장시키는 일을 합니다.
>  When atop is installed, the script atop.daily is stored in the /usr/share/atop directory.  This scripts takes care that atop is activated every day at midnight to write compressed binary data to the file /var/log/atop/atop_YYYYMMDD with an interval of 10 minutes.

그렇게 저장된 파일은 이름을 atop에 -r 플래그를 통해 전달하여 불러올 수 있습니다.
> A  raw  file  can be read and visualized again with the flag -r followed by the filename.

불러온 raw 파일은 저장된 내용을 10분 간격으로 앞 뒤로 넘겨보면서 볼 수 있습니다.

t를 눌러 다음 샘플로, T를 눌러 이전 샘플로, b를 눌러 ????, r을 눌러 파일의 시작으로 갈 수 있습니다.
>  The samples from the file can be viewed interactively by using the key 't' to show the next sample, the key 'T' to show the previous sample, the key 'b' to branch to a particular time or the key 'r' to rewind to the begin of the file.

또, 다음 플래그가 유용해 보입니다.

플래그 | 설명
------------ | -------------
d | 디스크와 관련된 정보를 봅니다.
v | 여러 내용을 봅니다. d를 눌렀다가 취소할 때 쓸 수 있다고 생각해주세요.
D | 디스크 접근 순으로 정렬합니다.
M | 메모리 순으로 정렬합니다.

그래서 `sudo atop -Ddr 20190417`라고 실행한다면, 2019년 4월 17일 로그를 보되, 디스크 정보를 표시하고 각 프로세스들은 디스크 접근 순으로 정렬됩니다.

혹은 위의 플래그들은 실행 중 단축키로도 쓸 수 있기 때문에, `sudo atop -r 20190417`로만 실행한 후 키보드의 `d`, `D`를 눌러 화면을 전환시킬 수 있습니다.

---------

그건 그렇다 치고, 우선 atop을 설치하면 raw 파일은 알아서 쌓이게 되므로, 다음과 같이 사용하면 좋을 것 같습니다.

1. 서버에 atop을 설치한다.
2. raw file이 잘 생성됐는지 확인한다.
3. 적당한 시간동안 방치한다.
4. raw file을 서버 밖으로 복사한다.
5. 서버에서 atop과 raw 파일 등을 삭제한다.
6. 로컬에서 atop으로 raw file을 분석한다.

**Comment by simnalamburt** [comment]
샘플링 주기가 10분인가요? https://unix.stackexchange.com/a/276086 여기엔 10초간격으로 샘플링하고 저장을 10분간격으로하는거라던데

만약에 10초간격으로 샘플링하는거면 충분할수도 있구요, 10분간격으로 샘플링하는거면 너무 기네요. (10분 사이에 발생한 Disk IO는 모를테니까) 0.5초 간격으로 하고싶은데.. 샘플링 주기 조절하는법만 조사해주시면 감사하겠습니다.

**Comment by 765P** [comment]
atop 샘플링 간격 조절에 대한 QnA 를 찾았습니다. https://unix.stackexchange.com/questions/276069/how-to-configure-atop-sampling-interval-log-path 간격조절을 위해서는 atop n 과 같은 식으로 이용하는 듯 합니다.

**Comment by simnalamburt** [comment]
atop 쩌네요. 리눅스 커널의 Process Accounting 기능을 써서, 인터벌 사이에 있었던 활동도 모조리 수집해서 출력해준답니다. 인터벌 길이 줄일 필요가 없겠어요. 프로세스당 부하 총합도 다 써있고, 저희가 원하는 기능은 다 있는것같습니다.

쓰기 전에 아래와 같이 리눅스 커널에서 Process Accounting, IO Accounting 등이 켜져있는지만 체크하면 된답니다.

```console
$ zcat /proc/config.gz | grep -E 'CONFIG_BSD_PROCESS_ACCT=|CONFIG_TASK_IO_ACCOUNTING='
CONFIG_BSD_PROCESS_ACCT=y
CONFIG_TASK_IO_ACCOUNTING=y
```

#### Reference
- https://www.atoptool.nl/download/man_atop-1.pdf
- https://www.linuxjournal.com/article/6144

**Comment by lens0021** [comment]
4/22/2019 16:09:12 ~ 2019/04/23 23:50:03 기간 중 (atop 로그에 찍힌 시간이고 타임존은 잘 모르겠습니다 하튼 중요한건 아니니까)

PID별 `RDDSK`와 `WRDSK`를 합친 비율:

![image](https://user-images.githubusercontent.com/28209361/57277659-96b56900-70df-11e9-8669-66e4e182b468.png)

PID에 따른, `RDDSK`와 `WRDSK`를 합친 값의 Stacked area chart:

![image](https://user-images.githubusercontent.com/28209361/57277795-dd0ac800-70df-11e9-91c4-b9ebf9045f6c.png)

`RDDSK` 합계와 `WRDSK`합계의 비교(Line chart):
![image](https://user-images.githubusercontent.com/28209361/57277883-01ff3b00-70e0-11e9-98ea-258ff2f85d0d.png)

치솟은 부분은 백업봇 가동 중일 때 같습니다.

**Comment by simnalamburt** [comment]
memcached와 카산드라가 직접적으로 발생시킨 Disk IO가 없는것은 아닌데, 그것보단 카산드라가 켜지면서 MySQL이 쓸 수 있는 메모리가 줄어 버퍼/캐시가 적어지면서 Disk IO가 많아진것이 더 큰 요인같다. EBS 타입을 standard에서 gp2로 바꾸는것으로 해결하자.

이와는 별개로 atop이 굉장히 유용했다. 지우지 말고 각 AMI들이 모두 설치해놓자

**Comment by simnalamburt** [comment]
볼륨 입출력을 줄일 필요가 없어졌으므로, 이 이슈는 닫고 https://github.com/femiwiki/femiwiki/issues/81 를 새로 열겠습니다.

**Comment by lens0021** [comment]
> 샘플링 주기가 10분인가요? https://unix.stackexchange.com/a/276086 여기엔 10초간격으로 샘플링하고 저장을 10분간격으로하는거라던데
> 
> 만약에 10초간격으로 샘플링하는거면 충분할수도 있구요, 10분간격으로 샘플링하는거면 너무 기네요. (10분 사이에 발생한 Disk IO는 모를테니까) 0.5초 간격으로 하고싶은데.. 샘플링 주기 조절하는법만 조사해주시면 감사하겠습니다.

위 내용에 대한 내용 우연히 찾아서 여기 남겨 놓습니다. 1분 간격으로 조정하는 예시입니다.

```sh
sudo sed -i 's/^LOGINTERVAL=600.*/LOGINTERVAL=60/' /etc/sysconfig/atop
sudo sed -i -e 's|*/10|*/1|' -e 's|every 10 minutes|every 1 minute|' /etc/cron.d/sysstat
```

https://aws.amazon.com/premiumsupport/knowledge-center/ec2-linux-configure-monitoring-tools/#Amazon_Linux_2
