### ISSUE TITLE
모든 리포지터리에 Continuous Delivery 세팅하기

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#69]
See https://github.com/femiwiki/femiwiki/issues/69#issuecomment-581119987

<details>
<summary>old description</summary>
현재 자체 확장기능들의 수정 혹은 새 확장기능의 설치/제거가 필요한 배포는 제가 대강 다음과 같이 하고있습니다.

```sh
cd mediawiki
git pull
docker stack rm mediawiki
watch docker volume rm mediawiki_files # 1
docker stack deploy -c production.yml --prune mediawiki # 2
```

1. mediawiki_files 볼륨을 삭제
2. docker deploy를 실행(실행 중 mediawiki_files 볼륨이 새로 생성됨)

덕분에 별거 안 할 때도 다운타임이 깁니다. 다른 방법이 있을까요?
(예: mediawiki_files를 볼륨으로 사용하는, 깃이 설치된 컨테이너를 잠시 띄워서 필요한 작업을 하고 끈다 등..)
</details>

**Comment by simnalamburt** [comment]
Kubernetes를 사용해 컨테이너들을 배포하기로했다. https://github.com/femiwiki/kubernetes 이 리포에 GitOps를 세팅해서 kubernetes YAML 파일들이 바뀔때마다 자동으로 배포되게 할 수 있고, 도커이미지에도 GitHub Actions를 사용해 변경사항이 생길때마다 자동으로 빌드되도록 만들 예정이다. (#51, #56) 확장기능의 경우 푸쉬할때마다 아래와 같이 [repository dispatch](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#external-events-repository_dispatch) API를 호출해서 docker-mediawiki 도커이미지를 재빌드 하는 방식으로 CD를 구현할 예정이다.

Sanctions는 실행할때마다 `php update.php`를 실행해줘야하는데 DB 테이블 구조 변경이 있을 수 있어서 CD 세팅이 쉽지않다.

```bash
curl \
  -XPOST \
  -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
  -H "Accept: application/vnd.github.everest-preview+json" \
  -H "Content-Type: application/json" \
  https://api.github.com/repos/YOURNAME/APPLICATION_NAME/dispatches \
  --data '{"event_type": "build_application"}'
```

### CD 세팅할 리포 목록
- [ ] kubernetes (쿠버 YAML)
- [x] infra (테라폼)

도커이미지
- [ ] docker-mediawiki
- [ ] docker-parsoid
- [ ] docker-restbase
- [ ] base
- [ ] base-extensions
- [ ] rankingbot
- [ ] backupbot
- [ ] tweetbot

확장기능
- [ ] 스킨
- [ ] Sanctions 
- [ ] UnifiedExtensionForFemiwiki
- [ ] FacetedCategory
- [ ] CategoryIntersectionSearch

그 외
- [x] remote-gadgets
- [ ] oojs-ui

**Comment by lens0021** [comment]
정보: 2020년 페미위키 운영팀의 1분기 목표는 "지속 가능한 페미위키 만들기"이며 이를 위해 개발팀은 "손으로 배포해야 하는 repository 3개 이하"를 목표로 잡았습니다. ([회의록](https://femiwiki.com/w/Special:Redirect/page/38255))

**Comment by simnalamburt** [comment]
@love-adela 님께서 도커이미지 CD를 거의 마무리하셨는데, 남은 확장기능들 CD하는것도 @love-adela 님과 @miriryu 님 두분이 마무리해주시면 어떨까 싶습니다

걍 확장기능에 새 커밋이 생길때마다 docker-mediawiki를 다시 빌드하면 됩니다

**Comment by lens0021** [comment]
CD 세팅이 완료된 리포들은 Branch protection을 고쳐서 master에서 수정하는 일을 막는 것에 administrators도 포함하는 것("Restrict who can dismiss pull request reviews" 체크박스를 해제하는 것)이 어떨까요?

**Comment by simnalamburt** [comment]
좋습니당

**Comment by lens0021** [comment]
> CD 세팅이 완료된 리포들은 Branch protection을 고쳐서 master에서 수정하는 일을 막는 것에 administrators도 포함하는 것("Restrict who can dismiss pull request reviews" 체크박스를 해제하는 것)이 어떨까요?

https://github.com/femiwiki/infra/issues/46 is opened

**Comment by simnalamburt** [comment]
쿠버 빼고 모든 repo CD 세팅 완료

**Comment by lens0021** [comment]
목록에 남은 항목이 하나 밖에 안 남아서 [https://github.com/femiwiki/femiwiki/issues/4](https://github.com/femiwiki/femiwiki/issues/4)가 열려있으면 충분할 것 같아 이 이슈 닫습니다.
