### ISSUE TITLE
하드디스크 장애 해결

### ISSUE THREAD

**Issue by simnalamburt** [femiwiki/femiwiki#70]
미디어위키 서버 하드디스크 용량이 꽉찼다. 대응 예상 소요시간은 60분.

```console
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        467M     0  467M   0% /dev
tmpfs           480M     0  480M   0% /dev/shm
tmpfs           480M   13M  468M   3% /run
tmpfs           480M     0  480M   0% /sys/fs/cgroup
/dev/nvme0n1p1  8.0G  8.0G   20K 100% /
tmpfs            96M     0   96M   0% /run/user/1000
```

1.  ~https://aws.amazon.com/premiumsupport/knowledge-center/expand-root-ebs-linux/ 이대로 대응하면 된다.~

2.  EBS 키우면 이슈 끝나긴 하는데, EBS 한번 키우면 다시 줄이기 매우 피곤하고 서버비용이 부담이 된다. 파일 삭제하는걸로 해결되는 이슈인지 먼저 확인하기위해 용량 꽉찬 원인 조사중이다.

3.  예상대로 도커이미지가 혼자서 다쓰고있었고, `/var/lib/docker` 혼자 5.8GiB를 쓰고있었다.

    ```console
    # docker system df
    TYPE                TOTAL               ACTIVE              SIZE                RECLAIMABLE
    Images              5                   2                   2.608GB             1.564GB (59%)
    Containers          2                   2                   87.2MB              0B (0%)
    Local Volumes       1                   1                   1.39GB              0B (0%)
    Build Cache         0                   0                   0B                  0B
    ```

4.  안쓰는 이미지 prune 시켰고 일단은 문제해결. 주기적으로 prune을 돌릴지, EBS를 키울지는 차후에 천천히 결정하도록 하자

**Comment by simnalamburt** [comment]
해결

**Comment by lens0021** [comment]
도커 이미지 치울 때 `docker image prune -a`로 지우면 되는 건가요?

**Comment by simnalamburt** [comment]
`docker system prune -fa --volumes` 이러시면 되는데 문제는 얘가 뭐가 댕글링 이미지이고 뭐가 댕글링 이미지가 아닌지 판단하는 기준이 엄격하지 않아서, 지워도 되는 이미지를 안지우는 경우가 있어요. 이번같은경우는 `femiwiki/mediawiki:build-0` 이미지를 손으로 지웠어요.
