### ISSUE TITLE
모니터링 개선하기

### ISSUE THREAD

**Issue by simnalamburt** [femiwiki/femiwiki#71]
- 서버 CPU, RAM, 하드디스크 사용량 등 모니터링 세팅하기 &rarr; https://github.com/femiwiki/femiwiki/issues/150
- [x] 장애시 알림오게하기 &rarr; https://github.com/femiwiki/femiwiki/issues/119

최대한 돈 덜 드는 솔루션을 찾아야함.

Related with #70

**Comment by lens0021** [comment]
CloudWatch alarm이 매트릭스 10개까지는 공짜라는 것 같습니다. 각 인스턴스들에 대해 CPUCreditBalance, 볼륨에 대해 BurstBalance이 일정 이상으로 내려갔을 때 admin@femiwiki.com으로 이메일이 오게 할 수 있을 것 같습니다.

다만 나중에 [오토스케일링](https://github.com/femiwiki/femiwiki/issues/2)을 하다가 필요한 알람이 10개보다 많아지면 어떻게 되는지.?가 문제입니다

#### References

- https://aws.amazon.com/cloudwatch/pricing/#Free_tier

**Comment by lens0021** [comment]
https://github.com/femiwiki/infra/issues/24 을 제외하면 더 달성할 목표가 없어서 이 이슈는 닫겠습니다
