### ISSUE TITLE
GSuite를 다른 서비스로 대체

### ISSUE THREAD

**Issue by simnalamburt** [femiwiki/femiwiki#72]
Migrated from https://github.com/femiwiki/mediawiki/issues/240

&nbsp;

# A. Mailgun
메일건은 받는건 제한 없는듯하고 보내는건 월 10000개가 있다

### 이메일 이전 계획
- [x] 도메인의 TTL을 최대한 낮게 맞춰줍니다. (너무 낮으면 도메인이 불안정해질 수 있으니 5분인 300정도로 맞춰주면 좋아요)
- [ ] AWS SES 프로젝트를 생성합니다.
- [ ] DNS에 TXT레코드를 추가하고, MX레코드를 변경합니다.
- [ ] 일단 이걸로 조치는 끝났지만, 아직 계속 메일은 구글로 올 것입니다. (일부 ISP나 기기에서 femiwiki.com의 dns를 분명 캐싱하고 있을 것이니까요)
- [ ] AWS SES의 Route 기능을 이용해서 메일을 받을 수 있는 이메일을 지정합니다.
- [ ] 외부 메일 연결을 하면 Mailgun의 SMTP주소로 메일을 보낼 수 있습니다. 웹을 통해 SMTP를 통해서 보낼 수 있는건 일부 서비스 업체에서 제공하긴 하던데... 일단 제가 아는 곳은 Nate밖에 없습니다.
- [ ] zapier 다시 설정
- [ ] 고생하셨습니다! 모두 끝났어요!

### 드라이브 이전 계획
- [x] 셰어드 드라이브로 옮긴 뒤 페미위키 지스윗 베이직플랜으로 낮추기
- [ ] 지스윗 삭제되어도 셰어드 드라이브 여전히 남아있는지 테스트하기
- [ ] 퍼블릭 공개 폴더 없애고 다른걸로 대체하기
- [ ] 소유자가 개인계정으로 되어있어 이동이 불가능한 파일들 옮기기. 소유자분들께 일일이 부탁하면 됨

&nbsp;

# B. Zoho Mail

**Comment by HanbitGaram** [comment]
이 내용은 페미위키 신입 운영진 환영회 때 논의된 사안으로,
GSuite가 상당히 자금을 많이 먹는 요인이므로 GSuite를 제거하고 Mailgun으로 페미위키의 Mail Service를 이전합니다.

준비해야 할 것

1. 도메인의 TTL을 최대한 낮게 맞춰줍니다. (너무 낮으면 도메인이 불안정해질 수 있으니 5분인 200정도로 맞춰주면 좋아요)

2. Mailgun에 가입합니다.

3. DNS에 TXT레코드를 추가하고, MX레코드를 변경합니다.

4. 일단 이걸로 조치는 끝났지만, 아직 계속 메일은 구글로 올 것입니다. (일부 ISP나 기기에서 femiwiki.com의 dns를 분명 캐싱하고 있을 것이니까요)

5. Mailgun의 Route 기능을 이용해서 메일을 받을 수 있는 이메일을 지정합니다. (갠적으로는 Google과 Nate를 추천드립니당)

6. Nate에 가입한 뒤, 외부 메일 연결을 하면 Mailgun의 SMTP주소로 메일을 보낼 수 있습니다. 웹을 통해 SMTP를 통해서 보낼 수 있는건 일부 서비스 업체에서 제공하긴 하던데... 일단 제가 아는 곳은 Nate밖에 없습니다.

7. 고생하셨습니다! 모두 끝났어요!

**Comment by lens0021** [comment]
저희 한달에 보내는 메일 수는 100~600 건 정도로 생각하면 될 것 같습니다.

![image](https://user-images.githubusercontent.com/28209361/58370748-0ed7b780-7f45-11e9-8dc8-6155eec78204.png)


https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#metricsV2:graph=~(metrics~(~(~'AWS*2fSES~'Send~(stat~'Sum~period~2592000)))~view~'timeSeries~stacked~false~region~'us-east-1~start~'-P1Y~end~'P0D);query=~'*7bAWS*2fSES*7d

**Comment by HanbitGaram** [comment]
![route_method](https://user-images.githubusercontent.com/18398825/58371040-b9050e80-7f48-11e9-9d53-9057955c203a.png)

개발은 완료하였습니다. - https://github.com/femiwiki/emailbot

사용하는 방법은 상기 이미지와 같습니다.

**Comment by simnalamburt** [comment]
G Suite 계정 정리할때 이관할 데이터 목록
- 메일
- 구글 드라이브
- 구글 아날리틱스

**Comment by simnalamburt** [comment]
@HanbitGaram 님과 @lens0021 님의 노력으로 G Suite Plan을 Business Plan(12 USD/month)에서 Basic Plan(6 USD/month)로 줄이는것에는 성공함. 그러나 페미위키에서 구글드라이브를 쓰는 이상 G Suite를 아예 없애진 못할것같고, 한빛가람님께서 테스트한 결과 G Suite 계정을 삭제하면 팀 드라이브도 같이 삭제되기때문에 공짜로 쓰기는 어려울것같다.

"지스윗 계정 안없애고 결제만 끊기"는 한빛가람님께서 아직 실험을 못하긴 하셨지만, 뭔가 정상적으로 드라이브를 운영할 수 있을 것 같지는 않아서 G Suite는 어쩔 수 없이 계속 써야할것같다.

**Comment by lens0021** [comment]
ttl은 300으로 유지하는 걸로 김지현님과 저의 합의?로 일단 결정되었습니다~
