### ISSUE TITLE
레플리카로 로컬 데이터베이스 운용

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#75]
> By using replicas when possible, site scalability is improved and wikis spanning multiple datacenters remain efficient by using local replica databases for all queries for most requests, rather than sometimes using the (remote) master database (from a read-only datacenter).
https://www.mediawiki.org/wiki/Database_optimization#Typical_read_queries

개발팀 회의에서 제안되었던 내용 중, 미디어위키는 원격 데이터베이스를 이용시 성능이 급격히 저하된다?는 말씀이랑 관련하여 레플리카를 운용하자는 이야기?(어떤 분이 하셨던 말씀인지랑 정확한 내용이 제가 정확히 안납니다 틀렸으면 코멘트로 정정해주세요ㅠ)가 있어서 조사 중 미디어위키에 관련한 기능이 있는 것 같아 이를 사용하여 [성능 최적화](https://github.com/femiwiki/femiwiki/issues/75)를 도모합니다.

Related with https://github.com/femiwiki/femiwiki/issues/60

#### References

- https://www.mediawiki.org/wiki/Database_optimization
- https://www.mediawiki.org/wiki/Manual:$wgDBservers
- https://www.mediawiki.org/wiki/Manual:$wgLBFactoryConf - 멀티 마스터용 설정이므로 참고만 하면 됩니다.

**Comment by HanbitGaram** [comment]
원격지 데이터베이스 서버와 웹 서버가 상호간 연결하는 시간이 있다보니 그 시간동안 PHP는 응답을 보류하게 되잖아요! 그 시간을 줄이기 위해 웹 서버 내에 DB서버 레플리카를 하나 만들자는 말씀이었습니다.

성능저하가 맞지만, 아무래도 의도치 않은 성능저하인거죠.

물론 처음 데이터를 받아올 때 웹 서버가 불안정한 상황은 아무래도 감수해야겠지만, 효율적이라고 생각합니다.

레퍼런스로 올려주신 두번째 링크는 생각대로 움직일지는 모르겠지만, 첫번째는 굉장히 도움이 되는 알짜배기들이 모여있어 유용하게 쓰이겠습니다.

**Comment by lens0021** [comment]
Closed by https://github.com/femiwiki/femiwiki/issues/117
