### ISSUE TITLE
IAM Role 티어 두개로 분리하기

### ISSUE THREAD

**Issue by simnalamburt** [femiwiki/femiwiki#76]
지금은 IAM Role이 딱 하나만 있고 그 Role에 모든 어드민 권한을 주고있어서 매우 위험함. 티어 두개로 분리해야한다.

**Comment by lens0021** [comment]
Closed by https://github.com/femiwiki/infra/commit/fb010d503a8af43131587743fa1b0494ea872ac1 ?

**Comment by simnalamburt** [comment]
Yes
