### ISSUE TITLE
database+bots 인스턴스 EBS 타입 standard에서 gp2로 바꾸기

### ISSUE THREAD

**Issue by simnalamburt** [femiwiki/femiwiki#81]
EBS standard 과금체계: GB당 0.08USD/month + 백만 리퀘스트당 0.08USD/month
EBS GP2 과금체계: GB당 0.12USD/month

4월달 총 EBS IO 수: 415235233회
4월달 총 EBS 용량: 24GiB

database+bots 인스턴스의 EBS 타입이 standard여서 35.14USD가 과금되었는데, 만약 저것들이 GP2였으면 2.88USD만 과금되었을것이다. 바꾸자

#### TODOs
- [x] standard에서 gp2로 바꾸기
- [x] 요금 줄어드는지 확인하기

#### Reference
- https://github.com/femiwiki/femiwiki/issues/64

**Comment by lens0021** [comment]
인스턴스를 한대 더띄워서 블루그린배포로 하는걸까요?

**Comment by simnalamburt** [comment]
AWS 문서에서 점검 없이 EBS 타입을 바꿀 수 있다는 말을 보고 즉시 타입을 변경했다.

2019-05-09T15:50+0900 시점에 standard에서 gp2로 변경 완료

###### Reference
- https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-modify-volume.html

**Comment by simnalamburt** [comment]
요금 줄어든것 확인함. Closing
