### ISSUE TITLE
레스트베이스(RESTBase) 재구동

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#82]
### 요약

EBS Volume을 st1에서 gp2로 바꾸고 난 이후 Burst Balance가 감소하여 2019-05-11 05:00+0900(추정)부터 페미위키 접속이 되지 않아 10:56+0900 카산드라를 끄고 난 이후 Burst Balance이 회복되었으나 카산드라 및 RESTBase를 다시 사용하지 못 하고 있습니다.

카산드라의 높은 리소스 사용량으로 인해 일어난 현상으로 생각되며, 생각할 수 있는 다음 세 가지 해결책 중 3번이 진행중입니다.

1. 다시 SQLite를 쓴다.
2. Cassandra를 최적화해 사용한다.
3. ~~RESTBase가 MySQL을 Backend Storage로 쓸 수 있도록 개변하여 사용한다 &rarr; https://github.com/femiwiki/femiwiki/issues/86~~

### 10:56+0900 이전 상황

![image](https://user-images.githubusercontent.com/28209361/57561764-b9d66600-73c8-11e9-8f6f-055334a61a14.png)

▲ GA 접속량 그래프, 점선이 어제, 실선이 오늘로 오전 5시부터 접속이 안 된 것으로 보입니다.

`mediawiki`인스턴스에서 `sql.php`를 실행할 경우 다음 에러가 발생했습니다
```
[d6b33fb643002eee68d1e69f] [no req]   Wikimedia\Rdbms\DBConnectionError from line 1195 of /srv/femiwiki.com/includes/libs/rdbms/loadbalancer/LoadBalancer.php: Cannot access the database: Unknown error (172.31.11.11)
Backtrace:
#0 /srv/femiwiki.com/includes/libs/rdbms/loadbalancer/LoadBalancer.php(769): Wikimedia\Rdbms\LoadBalancer->reportConnectionError()
#1 /srv/femiwiki.com/maintenance/sql.php(85): Wikimedia\Rdbms\LoadBalancer->getConnection(integer, array, boolean)
#2 /srv/femiwiki.com/maintenance/doMaintenance.php(94): MwSql->execute()
#3 /srv/femiwiki.com/maintenance/sql.php(205): require_once(string)
#4 {main}
```

[https://femiwiki.com/femiwiki.com/v1/page/html/페미위키:대문](https://femiwiki.com/femiwiki.com/v1/page/html/%ED%8E%98%EB%AF%B8%EC%9C%84%ED%82%A4:%EB%8C%80%EB%AC%B8)은 Caddy에 의해 RESTBase로 리다이렉트 되어 캐쉬된 페미위키:대문을 보여주는 URL인데 접속시 `{"type":"https://mediawiki.org/wiki/HyperSwitch/errors/query_error","title":"Error in Cassandra table storage backend","method":"get","uri":"/femiwiki.com/v1/page/html/%ED%8E%98%EB%AF%B8%EC%9C%84%ED%82%A4%3A%EB%8C%80%EB%AC%B8"}`라는 메시지만을 표시합니다. 그러나 이것을 토대로 Caddy와 RESTBase는 정상적으로 동작중이라고 추측해볼 수 있습니다.

참고로 5시에 자동으로 실행되는 작업들의 결과는 다음과 같습니다

- 데이터베이스 백업 &rarr; S3에 `2019-05-11T05:00+09:00.sql.gz`파일이 생성되어 있는 것을 확인, 용량도 다른 백업과 비슷함
- 트윗봇 &rarr; 트윗을 잘 한 것을 확인 https://twitter.com/Femiwikidotcome/status/1126940018616856576
- 6시에 실행하게 되어 있던 랭킹봇은 실행되지 않은 것으로 보입니다.

`df -h`와 `free -m` 결과는 특별한 점 없었던 걸로 기억합니다

### 장애 발생 후 실행한 작업

- 08:13+0900 mediawiki_bots 인스턴스 리부트함
- 08:23+0900 `docker stack rm bots` 실행함
```shell
$ docker stack rm bots
Removing service bots_backupbot
Removing service bots_ranking-bot
Removing service bots_tweetbot
Removing network bots_default
Failed to remove network f37shqc8j41258rdmgmgy0uzk: Error response from daemon: rpc error: code = DeadlineExceeded desc = context deadline exceededFailed to remove some resources from stack: bots
```
- 10:46+0900 mediawiki_bots 인스턴스 리부트함
- 10:56+0900 `docker stack rm cassandra` 실행함, 59분까지 반응 없다가 다음 출력과 함께 실행완료
```
Removing service cassandra_cassandra
Removing network cassandra_default
```
- 11:03+0900 
```shell
$ docker stack rm bots
Removing network bots_default
```
- 11:07+0900
```
$ docker stack deploy --prune -c ~/swarm/bots.yml bots
Creating network bots_default
Creating service bots_tweetbot
Creating service bots_ranking-bot
Creating service bots_backupbot
```

- 11:12+0900 LocalSettings.php 다음 라인을 주석처리 &rarr; https://github.com/femiwiki/mediawiki/blob/f34320781f4ba988c92ebda5e0e1b1d3a00c6e1d/configs/LocalSettings.php#L277-L282

**Comment by lens0021** [comment]
![image](https://user-images.githubusercontent.com/28209361/57563886-93232a00-73de-11e9-8454-d82e49529a44.png)

위와 같이 05:00+0900부터 CPU 사용량이 증가되어 있었다가 카산드라 콘테이너를 끈 직후 급감하였고, 몇 분 유예 후에 페미위키 접속이 이전과 같이 잘 되기 시작했습니다. 원인을 파악하지 못 하였기 때문에 카산드라를 다시 켜기는 조심스럽고 봇들은 상관 없어 보여 켰습니다.

**Comment by lens0021** [comment]
카산드라 로그가 남았을까 해서 종료된 콘테이너를 찾았지만 다음과 같았습니다.

```shell
$ date && docker container ls -a
2019. 05. 11. (토) 02:48:22 UTC
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS                           PORTS                 NAMES
204efcb8b49a        femiwiki/backupbot:build-5    "/tini -- /a/docker-…"   40 minutes ago      Up 40 minutes                                          bots_backupbot.1.55hhhkosie5dp9u2dr9tw422m
86e0afe4d1a4        femiwiki/rankingbot:build-0   "/tini -- /bin/sh -c…"   40 minutes ago      Up 40 minutes                                          bots_ranking-bot.1.b0pguszxrfixi5dv0zprxrwq2
d2b8c9242331        femiwiki/tweetbot:build-0     "/tini -- /a/docker-…"   40 minutes ago      Up 40 minutes                                          bots_tweetbot.1.qcrkaiu0bqprefhet6bb0jd58
e7040e77be44        memcached:1-alpine            "docker-entrypoint.s…"   About an hour ago   Up About an hour                 11211/tcp             memcached_memcached.1.ug0pehe9v62tnzyz2g8238273
2d4a8a012493        mysql:8                       "docker-entrypoint.s…"   About an hour ago   Up About an hour                 3306/tcp, 33060/tcp   database_mysql.1.4ubrtrj0f1062g9y59nk3kebu
82a17f84c030        mysql:8                       "docker-entrypoint.s…"   About an hour ago   Exited (137) About an hour ago                         database_mysql.1.dsdbg36umh5nmvzqodidm3k0n
da5710ccd292        memcached:1-alpine            "docker-entrypoint.s…"   About an hour ago   Exited (0) About an hour ago                           memcached_memcached.1.a4ad03zdmfm9k3zdopkprvrrn
11cf19a67a21        memcached:1-alpine            "docker-entrypoint.s…"   About an hour ago   Exited (255) About an hour ago   11211/tcp             memcached_memcached.1.2nud63yy71sp2epeotnofzuok
26cbda0c0768        mysql:8                       "docker-entrypoint.s…"   About an hour ago   Exited (255) About an hour ago   3306/tcp, 33060/tcp   database_mysql.1.8nuyclytqvo0od0u5yo0s9w94
03adccbd9c02        mysql:8                       "docker-entrypoint.s…"   About an hour ago   Dead                                                   database_mysql.1.m127i8fgjlc6ewhpy8v3z1hro
66ee75225056        memcached:1-alpine            "docker-entrypoint.s…"   2 hours ago         Dead                                                   memcached_memcached.1.zpo1n55snolq4evipmbljlc38
f20d15bfa279        femiwiki/rankingbot:build-0   "/tini -- /bin/sh -c…"   3 hours ago         Exited (143) 3 hours ago                               bots_ranking-bot.1.4w38ig6sohhyf1n6ut3gfses8
afbd04e690cd        femiwiki/tweetbot:build-0     "/tini -- /a/docker-…"   6 hours ago         Created                                                bots_tweetbot.1.48ak0hg9e841xmngu1cec9i7x

```

**Comment by simnalamburt** [comment]
장애가 발생한 시점 부근인 `2019-05-11T05:00+0900`, UTC로 `2019-05-10T20:00Z` 시점의 atop 로그를 확인해보았다

```
atop -r ./atop_20190510 -b 19:40
# 그리고 t와 T 키로 앞뒤 타임프레임을 보면 됨
```

그 결과 아래와 같이 IO에 병목이 걸린것을 확인함

```
DSK |      nvme0n1 | busy     99%  | read   38594 | write  23378 | KiB/r      8 |  KiB/w      4 | MBr/s    0.5 | MBw/s    0.2 |  avq    24.35 | avio 9.68 ms |
```

EBS 볼륨의 IO Burst Balance를 확인한 결과, Burst Balance가 0이 된 시점과 장애가 발생한 시점이 정확히 일치한다.

<img width="588" alt="스크린샷 2019-05-11 오후 2 26 37" src="https://user-images.githubusercontent.com/4435445/57565610-ddff6a80-73fb-11e9-83b4-649ccd264a31.png">

<img width="891" alt="스크린샷 2019-05-11 오후 2 27 30" src="https://user-images.githubusercontent.com/4435445/57565612-dfc92e00-73fb-11e9-964b-df652949834d.png">

**Comment by simnalamburt** [comment]
카산드라 디스크 IO 튜닝을 하면 해결될것으로 보인다 https://medium.com/linagora-engineering/tunning-cassandra-performances-7d8fa31627e3

**Comment by lens0021** [comment]
> Cassandra's default configuration attempts to consume between 800M and 4G of memory for its heap, which can be a substantial fraction of total memory available on a developer's local machine.
> ...
>
> \- [Tweaking Cassandra for testing](https://www.mediawiki.org/w/index.php?title=Parsoid/Setup/RESTBase&oldid=1865021#Tweaking_Cassandra_for_testing
), Parsoid/Setup/RESTBase

**Comment by lens0021** [comment]
카산드라는 포기하고 이를 MySQL로 대체(https://github.com/femiwiki/femiwiki/issues/86)한 이후에 재구동 가능할 것으로 보입니다.

**Comment by lens0021** [comment]
https://github.com/femiwiki/femiwiki/issues/149 로 대체됨
