### ISSUE TITLE
EC2 Instance Connect

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#9]
#### Activity
- Hyeon Kim added [this card](https://trello.com/c/Tl2vCfhz) to To Do - Sep 6 at 7:02 PM
- Hyeon Kim joined this card - Sep 6 at 7:03 PM
- 낙엽 transferred this card from [FEMIWIKI](https://trello.com/b/zX0oXA4U) - Sep 11 at 2:09 AM

**Comment by simnalamburt** [comment]
볼트세팅을 하려면 콘술클러스터를 세팅해야하는데, 지금 카산드라도 돈없어서 못켜는마당에 콘술클러스터는 돈문제때문에 못띄울것같다. 대신 AWS EC2 Instance Connect는 무료로 쓸 수 있을것같다.

**Comment by lens0021** [comment]
> Amazon Linux 2 2.0.20190618 or later comes preconfigured with EC2 Instance Connect.

위 내용 언급 주셨었는데, 버전 정보를 어떻게 확인하는지를 모르겠네요

```sh
$ cat /etc/*release*
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
Amazon Linux release 2 (Karoo)
cpe:2.3:o:amazon:amazon_linux:2
```
```sh
$ cat /etc/issue
\S
Kernel \r on an \m
```
```sh
$ uname -a
Linux ip-172-31-36-91.ap-northeast-1.compute.internal 4.14.146-120.181.amzn2.x86_64 #1 SMP Fri Oct 18 17:01:06 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by lens0021** [comment]
> Instance Connect was successfully installed if the AuthorizedKeysCommand and AuthorizedKeysCommandUser lines in the /etc/ssh/sshd_config file contain the following values:
> 
> ```
> AuthorizedKeysCommand /opt/aws/bin/eic_run_authorized_keys %u %f
> AuthorizedKeysCommandUser ec2-instance-connect
> ```
> --https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-set-up.html#ec2-instance-connect-install

위 안내에 따라 해당 파일을 찾아보니

```
#AuthorizedKeysCommand none
#AuthorizedKeysCommandUser nobody
```

라고 되어 있어 설치가 필요해 보입니다.

**Comment by simnalamburt** [comment]
버전문제때문은 아니고 Amazon Linux 2 미니멀버전을 써서 안깔려있는거같네요

**Comment by lens0021** [comment]
`sudo yum install ec2-instance-connect` 및 https://github.com/femiwiki/infra/commit/209de92 적용 후 [Connect Using EC2 Instance Connect](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-methods.html) 문서에서 설명된 셋 중 Browser-based Client과 SSH Client가 잘 되는 것을 확인했습니다. `mssh i-001234a4bf70dec41EXAMPLE`은 하는 법을 잘 모르겠습니다.

**Comment by lens0021** [comment]
`mssh i-001234a4bf70dec41EXAMPLE`도 되는 거 확인했습니다.

**Comment by lens0021** [comment]
Todo 아직 완료 안돼서 다시 엽니다
