### ISSUE TITLE
Saving Plan 구입하기

### ISSUE THREAD

**Issue by simnalamburt** [femiwiki/femiwiki#92]
t3a.micro 1년 full upfront로 사자

#### TODO
- [x] 구매신청하기
- [ ] 결제 및 적용여부 확인하기

#### References

- https://aws.amazon.com/about-aws/whats-new/2019/11/introducing-savings-plans/
- https://aws.amazon.com/savingsplans/pricing/

**Comment by lens0021** [comment]
Close as duplicate of https://github.com/femiwiki/femiwiki/issues/87

**Comment by lens0021** [comment]
같은건지 알고 닫았다가 열었습니다.

질문입니다, RI로 구입하면 https://github.com/femiwiki/femiwiki/issues/2 은 그만큼 연기하는 건가요 아니면 인스턴스 하나는 항상 켜있고 그 이상을 오토스케일링하도록? 하는 등 방식을 쓰는 건가요?

**Comment by simnalamburt** [comment]
#2 는 연기에요

**Comment by simnalamburt** [comment]
https://aws.amazon.com/blogs/aws/new-savings-plans-for-aws-compute-services/

RI 대신 이거 사면 될듯

**Comment by simnalamburt** [comment]
1. Compute Savings Plans: 기존의 컨버터블 RI가 더 유연해진것. 더 비쌈
2. EC2 Instance Savings Plans: 기존의 스탠다드 RI. 더 쌈

t3a.micro 1대, 리눅스, 1년 All Upfront, Shared Tenancy 기준으로

1. Compute Savings Plans: 0.009 USD/hour = 78.894 USD/year = 92925.7951 KRW/year
2. EC2 Instance Savings Plans: 0.0078 USD/hour = 68.3748 USD/year = 80535.689 KRW/year

**Comment by simnalamburt** [comment]
2019-11-22 ~ 2020-11-21 동안 도쿄 리전에서 적용되는 EC2 Instance Saving Plan t3a 타입으로 구매했고, Commitment는 0.008 USD/hour 입니다.

결제 되는거 기다리고, Saving Plans Utilization Report에 할인 적용되는거 보이기 시작하면 닫으면 될거같아요

**Comment by simnalamburt** [comment]
잘 적용됨, 구매완료
