### ISSUE TITLE
LB(Load Balancer) 떼기

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#93]
#### 점검 시나리오

- [x] `tls.dns.route53` 플러그인이 활성화된 Caddy 1.0.3 도커이미지 준비 &rarr; [`femiwiki/caddy:1.0.3`](https://cloud.docker.com/u/femiwiki/repository/docker/femiwiki/caddy) &rarr; https://github.com/femiwiki/mediawiki/commit/fe10b15
- [x] `aws_instance.mediawiki`에 route53 권한 주기, 미디어위키 인스턴스 SG 고쳐서 80/443 요청 받을 수 있도록 수정 &rarr; https://github.com/femiwiki/infra/issues/4
- [x] 인증서 작업 해서 caddy가 HTTP/HTTPS 둘다 서빙할 수 있도록 수정 &rarr; https://github.com/femiwiki/mediawiki/pull/298
- 새 인스턴스(`aws_instance.mediawiki_green`) 런치하여 HTTPS 서빙하도록 하기 &rarr; **리밋걸림** 

> 2019/10/31 09:45:26 [ERROR][femiwiki.com] failed to obtain certificate: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many certificates already issued for exact set of domains: femiwiki.com: see https://letsencrypt.org/docs/rate-limits/, url:  (attempt 1/3; challenge=dns-01)

----

- [x] Revert https://github.com/femiwiki/mediawiki/commit/1d50ae9: `www.femiwiki.com`도 서빙할 수 있도록 와일드카드를 포함한 레이블을 Caddyfile에 추가 &rarr; https://github.com/femiwiki/mediawiki/commit/a8891da
- [x] 패커 이용하여 새 AMI 빌드
- [x] 도커 이미지 새로 빌드하고 컴포즈 파일 태그 고쳐야함
- [x] Revert https://github.com/femiwiki/mediawiki/commit/b529fde
- [x] 테라폼 코드에서 인스턴스 프로필 및 주석처리된 새 인스턴스(`aws_instance.mediawiki_green`)를 주석 해제하고 AMI를 위에서 빌드한 것으로 변경
- [x] 런치 템플릿 활용도 떨어져서 삭제함 &rarr; https://github.com/femiwiki/infra/commit/9d76545
- [x] `ami-0f33723c4705b70d5` 삭제
- [x] `terraform apply`로 새 인스턴스 런치, 이 때 다음도 같이 확인하면 좋음:
  - [x] atop 잘 설치되었는지(https://github.com/femiwiki/ami/issues/1)
  - [x] https://github.com/femiwiki/infra/issues/9 이슈 해결 여부
- [x] `~/mediawiki/configs/secret.php` 적절한 내용으로 생성
- [x] 새 인스턴스 HTTPS 서빙하도록 하기
- [x] `aws_route53_record.femiwiki_com` 및 `aws_route53_record.www_femiwiki_com` DNS 변경, femiwiki.com 도메인이 ALB가 아니라 인스턴스를 가리키도록 수정 &rarr; https://github.com/femiwiki/infra/pull/6

----

- [x] caddy가 HTTP 연결을 아예 금지시켜버리니까 parsoid가 동작 안하게되어서, parsoid만 한정으로 허용해줌 https://github.com/femiwiki/mediawiki/compare/e5cb50..9a0520
- [x] [ALB에 트래픽 없어지는것 확인한 뒤][alb-monitor] ALB와 ALB 관련자원들(sg, route53, iam) 삭제(&rarr;https://github.com/femiwiki/infra/pull/5)
- [x] 이전 인스턴스 삭제
- [x] `terraform state mv aws_instance.mediawiki_green aws_instance.mediawiki`하고 코드에 적힌 이름도 바꾸기
- [x] femiwiki-mediawiki 옛날 AMI 지우기
- [x] 모두 끝난 뒤 Qualys SSL Labs에 테스트시켜서 A+ 나와야함. https://www.ssllabs.com/
- [x] LB 떼어서 비용절감한 부분 CHANGELOG.md 에 기록하고 페미위키 팀 전체에 공유

[alb-monitor]: https://ap-northeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-northeast-1#metricsV2:graph=~(metrics~(~(~'AWS*2fApplicationELB~'RequestCount~'LoadBalancer~'app*2ffemiwiki-load-balancer*2febeed3504104bc38~'AvailabilityZone~'ap-northeast-1a~(visible~false))~(~'.~'.~'.~'.))~view~'timeSeries~stacked~false~region~'ap-northeast-1~start~'-PT1H~end~'P0D~stat~'Sum~period~60)

**Comment by simnalamburt** [comment]
끝난 뒤 SSL 테스트해봅시다 https://www.ssllabs.com/ 투두에넣음

**Comment by simnalamburt** [comment]
A+ 받음

https://www.ssllabs.com/ssltest/analyze.html?d=femiwiki.com

<img width="1006" alt="스크린샷 2019-11-09 오전 12 34 40" src="https://user-images.githubusercontent.com/4435445/68488596-bee97480-0288-11ea-9607-4626ba21daa2.png">

**Comment by lens0021** [comment]
https://github.com/femiwiki/mediawiki/blob/dac2960524eed7cd6929c4187b54f353cdaed4d7/configs/secret.php.example#L6-L8

이거 지워야 하는데 안 지워서 지금 지우겠습니다
