### ISSUE TITLE
Zoho Mail 조사

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#94]
[Zoho Mail] 사용이 가능할 지, 사용한다면 장단점은 무엇인지 등 조사

[zoho mail]: https://www.zoho.com/mail/

**Comment by 765P** [comment]
zoho 메일 소개글에 따르면 광고로부터 자유로운 메일이라 소개하고 있음. 아래 장단점 표를 추가적으로 첨부하도록 하겠음
![image](https://user-images.githubusercontent.com/12128925/65849701-98c9de00-e386-11e9-9ac4-beb5f0575b3b.png)

**Comment by simnalamburt** [comment]
zoho는 최근엔 무료 플랜 인원제한이 5인으로 줄었네요

**Comment by HanbitGaram** [comment]
![image](https://user-images.githubusercontent.com/18398825/65856734-552e9e80-e39d-11e9-90c5-ec949fe95ab3.png)

일단 여러가지 기능도 많고 쓰기도 좋아요.
근데 앱이 안좋아요.

iOS 기본 메일앱이랑 다를 것이 무엇인가
![image](https://user-images.githubusercontent.com/18398825/65856983-de45d580-e39d-11e9-9c44-da272c9c855e.png)

**Comment by simnalamburt** [comment]
Closed as duplicate of https://github.com/femiwiki/femiwiki/issues/72
