### ISSUE TITLE
각종 비용 절감

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#96]
- [x] [서버 비용 절감](https://github.com/femiwiki/femiwiki/issues/32): 클라우드 서비스에 지불되는 비용을 절감합니다.
- ~~[이메일로 인한 비용](https://github.com/femiwiki/femiwiki/issues/72): 이메일 사용과 관련하여 지불되는 비용을 절감합니다.~~
- [x] [Zapier 대체](https://github.com/femiwiki/femiwiki/issues/100): 사용중인 유료 협업 툴을 더 저렴한 방법으로 대체합니다.

2019년 4사분기 목표: 월고정비 8만원

**Comment by simnalamburt** [comment]
### Before
(2019년 1~10월 비용 평균)

항목 | USD/month
----|----
AWS | 103.051
Zapier | 19.99
G Suite | 12
**총합** | 135.041 (=156480.11 KRW/month)

### After

항목 | USD/month
----|----
AWS 인스턴스비 | 5.666990 (선불)
AWS 트래픽+EBS | 6.442
AWS S3 | 2.528
AWS Route53 | 0.321
AWS 도메인비용 | 1.200
AWS 세금 | 5.198
Zapier | 0
G Suite | 6
**총합** (선불 포함) | 27.35599 (=32,300.59 KRW/month)
**총합** (선불 제외) | 21.689 (=25,609.29 KRW/month)
