### ISSUE TITLE
Docker Hub 대신 GitHub Container Registry 사용

### ISSUE THREAD

**Issue by lens0021** [femiwiki/femiwiki#97]
- [x] 배포중인 콘테이너 리스트업하기
  <details>
  <ul>
  <li>femiwiki/base</li>
  <li>femiwiki/base-extensions</li>
  <li>femiwiki/mediawiki</li>
  <li>femiwiki/parsoid</li>
  <li>femiwiki/restbase</li>
  <li>femiwiki/backupbot</li>
  <li>femiwiki/caddy</li>
  </ul>
  </details>
- [x] https://github.com/organizations/femiwiki/settings/member_privileges#package_creation
- [x] Create a PAT with `read:packages` and `write:packages` scopes and save it as an Actions secret `CR_PAT`
- Create secrets on repositories
  - [x] https://github.com/femiwiki/base/settings/secrets
  - [x] https://github.com/femiwiki/base-extensions/settings/secrets
  - [x] https://github.com/femiwiki/docker-parsoid/settings/secrets
  - [x] https://github.com/femiwiki/docker-restbase/settings/secrets
  - [x] https://github.com/femiwiki/backupbot/settings/secrets
  - [x] https://github.com/femiwiki/docker-mediawiki/settings/secrets
- GitHub Container Registry로 옮기기 https://github.blog/2020-09-01-introducing-github-container-registry/
  - Migrate publish steps in Github Actions ([example](https://github.com/actions/starter-workflows/blob/188a1b09954720a23d484ebd4d825160cc174c6f/ci/docker-publish.yml))
    - [x] femiwiki/base
    - [x] femiwiki/base-extensions
    - [x] femiwiki/parsoid
    - [x] femiwiki/restbase
    - [x] femiwiki/backupbot
    - [x] femiwiki/mediawiki
  - Log in as the bot and add a team or users with read access to the container<sup>[[1]](https://github.community/t/github-packages-not-showing-up-in-organization-packages-ui/130481/2?u=lens0021)</sup>
    - [x] https://github.com/orgs/femiwiki/packages/container/base/settings
    - [x] https://github.com/orgs/femiwiki/packages/container/base-extensions/settings
    - [x] https://github.com/orgs/femiwiki/packages/container/parsoid/settings
    - [x] https://github.com/orgs/femiwiki/packages/container/restbase/settings
    - [x] https://github.com/orgs/femiwiki/packages/container/backupbot/settings
    - [x] https://github.com/orgs/femiwiki/packages/container/caddy/settings
    - [x] https://github.com/orgs/femiwiki/packages/container/mediawiki/settings
  - [x] Replace old image ids
- [x] [Deactivating an organization](https://docs.docker.com/docker-hub/deactivate-account/#deactivating-an-organization)
- [x] Delete Access Token on Docker Hub
- [x] Remove useless secrets
  - [x] https://github.com/femiwiki/base/settings/secrets
  - [x] https://github.com/femiwiki/base-extensions/settings/secrets
  - [x] https://github.com/femiwiki/docker-parsoid/settings/secrets
  - [x] https://github.com/femiwiki/docker-restbase/settings/secrets
  - [x] https://github.com/femiwiki/backupbot/settings/secrets
  - [x] https://github.com/femiwiki/docker-mediawiki/settings/secrets
- [x] Caddy 이미지 빌드 커맨드 문서화 등 어떻게 할지 결정 &rarr; `femiwiki/caddy:1.0.3` 그대로 `ghcr.io/femiwiki/caddy:1.0.3`로 새로 푸시함
- ~~Zapier에서 웹훅 래퍼 제거~~ → 트렐로로 옮김
- ~~Github에서 @femiwiki-bot account 지우기?~~ → 테라폼 클라우드 봇 토큰이 쓰고 있고 아직 활용도가 있어 보임

**Comment by lens0021** [comment]
Blocked by https://github.community/t5/GitHub-Actions/docker-pull-from-public-GitHub-Package-Registry-fail-with-quot/td-p/32782

**Comment by simnalamburt** [comment]
> Docker Hub에서 Docker Organization 지우기

찬성

**Comment by lens0021** [comment]
https://github.blog/2020-09-01-introducing-github-container-registry/ :tada::tada:

**Comment by simnalamburt** [comment]
고생 많으셨습니다

**Comment by simnalamburt** [comment]
ㄷㄷ 아래 경고문들 낙엽님께서 일일이 달으신건가여

![image](https://user-images.githubusercontent.com/4435445/92336320-40dd4080-f0da-11ea-914c-a9c1f380462c.png)

**Comment by simnalamburt** [comment]
Docker Hub을 가리키고 있던 각 리포의 배지들 모두 ![](https://badgen.net/badge/icon/docker?icon=docker&label)로 변경하고, 링크도 GitHub Container Registry로 바꿨습니다.

**Comment by lens0021** [comment]
> ㄷㄷ 아래 경고문들 낙엽님께서 일일이 달으신건가여
> 
> ![image](https://user-images.githubusercontent.com/4435445/92336320-40dd4080-f0da-11ea-914c-a9c1f380462c.png)

조직을 비활성화할 때 "비활성화 하면 리포들이 사라집니다" 이러길래 한 번에 다 사라질지 알고 리포 삭제 대신 조직 비활성화를 먼저 했는데 안 사라져서 경고문을 넣으려다가 편집 버튼이 점점 사라져서 몇 개는 추가하고 안 된 건 말았습니다 💦
